### ISSUE TITLE
Feature Request: Using grant as a middleware

### ISSUE THREAD

**Issue by bitinn** [simov/grant#10]
Looking at the koa consumer: https://github.com/simov/grant/blob/master/lib/consumer/koa.js

It seems this is essentially a wrapper for koa middleware, it would be great if we can use grant as a middleware (attach onto koa `this` context maybe), instead of mounting it as a koa app.

This avoid dependency problem mentioned in #9 and make it a lot more flexible when used with various session backend.

**Comment by simov** [comment]
What you are looking at is in fact a middleware. Can you give me a short code example showing what are the other possible options to define a middleware?

**Comment by bitinn** [comment]
I mean avoid having to do `mount`.

With `mount` you are essentially wrapping oauth into it's own koa app, and since it's a koa app, it comes with koa module dependencies, and creating problems for project that use a different session solution, or even just a different version of the same module.

It would be more flexible to transform koa `this` context alone, and leave router and session management independent (abstract them so that developers can write adapters to make other modules to work with `grant`).

**Comment by simov** [comment]
@bitinn check out this commit https://github.com/simov/grant/commit/920480633cdb221c6c73da9fbda9e29d4de2b5fb

The Koa middleware no longer require specific session store to use, **but** it is required to use one and set it before mounting grant.

I tested it with a bunch of session store modules here https://github.com/simov/grant/tree/master/example/koa-session

I'll update the docs prior releasing the new version (which will be around the end of this week)

This solves the session issues.

---

As for the koa-router module take a look at the examples again https://github.com/simov/grant/tree/master/example/koa-session there in my consumer application I'm using koa-route instead. So using koa-router is not required. As far as the middleware order goes, you should put session and grant on top, if mounting koa-router before grant doesn't work, then you should put it after it.

Closes https://github.com/simov/grant/issues/11
Closes https://github.com/simov/grant/issues/9

**Comment by simov** [comment]
@bitinn check out this commit https://github.com/simov/grant/commit/908b9a833f742a7a6b525d343a60369813106b6e

The Koa middleware no longer depends on koa-router, so you can mount it in your app wherever you want. I'll let you know when the new release is out.

**Comment by bitinn** [comment]
Thx, i will get to test it soon :)

**Comment by simov** [comment]
@bitinn version 3.0.3 is published on NPM. Thanks for the feedback :+1:
