### ISSUE TITLE
koa access_token missing from session

### ISSUE THREAD

**Issue by drvan** [simov/grant#100]
I cloned the `examples/koa-session-stores` example, filled in my provider's details and received the following error, despite the flow working successfully, indicating the the `grant` attribute was never added to the `session`:
```
Koa server listening on port 3000

  TypeError: Cannot read property 'response' of undefined
      at Object.<anonymous> (/private/var/tmp/grant/examples/koa-session-stores/koa-session.js:23:51)
      at Generator.next (<anonymous>)
      at Object.dispatch (/private/var/tmp/grant/examples/koa-session-stores/node_modules/koa-router/lib/router.js:317:7)
      at dispatch.next (<anonymous>)
      at Object.allowedMethods (/private/var/tmp/grant/examples/koa-session-stores/node_modules/koa-router/lib/router.js:356:5)
      at allowedMethods.next (<anonymous>)
      at onFulfilled (/private/var/tmp/grant/examples/koa-session-stores/node_modules/co/index.js:65:19)
      at /private/var/tmp/grant/examples/koa-session-stores/node_modules/co/index.js:54:5
      at new Promise (<anonymous>)
      at Object.co (/private/var/tmp/grant/examples/koa-session-stores/node_modules/co/index.js:50:10)
```

If I change the transport to `querystring`, the `access_token` is available in `this.query`. The exact same `config.json` works with the `examples/session-transport` example (which uses express) but I can't seem to get the `access_token` to be properly stored in the session object with the koa-session example. It looks looks like the session object contains only the state, nonce, provider, and expiration. Very possible I'm misunderstanding the docs somewhere along the way.

**Comment by simov** [comment]
Can you post your configuration here (without the app credentials), and possibly the server code if you have something different than the example.

**Comment by drvan** [comment]
Sure! Here's essentially the koa-session-stores, with a minor update to use koa2:
```js
var Koa = require('koa')
var session = require('koa-session')
var mount = require('koa-mount')
var Router = require('koa-router')
var koaqs = require('koa-qs')
var grant = require('grant-koa')
var config = require('./config.json')

var app = new Koa()
var router = new Router();
app.keys = ['grant']
app.use(session(app))
app.use(mount(grant(config)))
koaqs(app)

router
  .get('/websec_callback', (ctx) => {
    // ctx.body = JSON.stringify(ctx.query, null, 2)
    ctx.body = JSON.stringify(ctx.session.grant, null, 2)
  })

app
  .use(router.routes())
  .use(router.allowedMethods())
  .listen(3000, () => console.log(`Koa2 server listening on port ${3000}`))
```
I'm using a private oidc provider that's backed by PingFederate, but here is the config:
```
{
  "defaults": {
    "protocol": "http",
    "host": "localhost:3000",
    "transport": "session"
  },
  "websec": {
    "access_url": "[REDACTED]",
    "authorize_url": "[REDACTED]",
    "key": "[REDACTED]",
    "secret": "[REDACTED]",
    "callback": "/websec_callback",
    "oauth": 2,
    "scope": [
      "openid",
      "profile"
    ],
    "scope_delimiter": " "
  }
}
```

As an additional test, I tested this with auth0 as a provider and everything worked correctly, so I'm leaning towards one of the following:
- There's a bug in the code that processes custom providers (I think this is pretty unlikely)
- My custom provider does something unusual/unexpected
- My custom provider returns too much data to be stored in a session cookie

That being said, none of the above make much sense if my custom provider works with the express example.

I also checked the contents of `session.response` on line 69 in `lib/consumer/koa2.js` and it *did* contain the `access_token`, but it seems to be thrown away at the redirect on line 70. 

Happy to do some troubleshooting/debugging if you can point me in the right direction.

**Comment by simov** [comment]
Try to remove the `profile` scope and test it again.

The [koa-session](https://github.com/koajs/session) middleware encodes the entire session in a cookie, not just the session ID. So when redirect occurs all that data must be encoded in the HTTP headers, and some servers may reject headers above certain length. 

I'm not seeing an option to control that behavior in koa-session, unless you specify an external session store to use.

Besides that Grant also plays a negative role in this by returning a `raw` key in the final response, which is a nested data structure that potentially can get quite big when encoded. So in the upcoming release I'm going to introduce a new option for limiting the response keys returned.

**Comment by drvan** [comment]
Thanks for the help - you were completely right - the cookie was too large. I recorded the flow in Chrome devtools and the console spit out the following error:

`Set-Cookie header is ignored in response from url: http://localhost:3000/connect/websec/callback?code=[REDACTED]. Cookie length should be less than or equal to 4096 characters.`

Unfortunately removing the `profile` scope didn't help, but I looked at the docs for koa-session and there's a `beforeSave(ctx, session)` hook that will allow modification of the session before saving. Per your suggestion, I just deleted the `raw` key and everything worked. Here's the final code - note to anyone else who sees this, there should be better checks for identifying the token presence. This was quick and dirty to validate the theory:
```js
var Koa = require('koa')
var session = require('koa-session')
var mount = require('koa-mount')
var Router = require('koa-router')
var koaqs = require('koa-qs')
var grant = require('grant-koa')
var config = require('./config.json')

var app = new Koa()
var router = new Router();
app.keys = ['grant']
app.use(session({
  beforeSave(ctx, sess) {
    if (sess.grant.hasOwnProperty('response')) {
      delete sess.grant.response.raw
    }
  },
}, app));
app.use(mount(grant(config)))
koaqs(app)

router
  .get('/websec_callback', async (ctx) => {
    // ctx.body = JSON.stringify(ctx.query, null, 2)
    ctx.body = JSON.stringify(ctx.session.grant, null, 2)
  })

app
  .use(router.routes())
  .use(router.allowedMethods())
  .listen(3000, () => console.log(`Koa2 server listening on port ${3000}`))
```

I really appreciate you taking the time to point me in the right direction!

**Comment by simov** [comment]
Thanks for the feedback, @drvan, this is really helpful! I'll let you know when the next release is out with the new option to limit the response data in Grant. :+1:

**Comment by simov** [comment]
Hi @drvan, I've published the [response option](https://github.com/simov/grant#limit-response-data).

Note that by default the `response: 'tokens'` will return all tokens as strings, including the `id_token`. That's the smallest possible response.

In case you want to include the decoded `id_token` in the response data you have to use `response: ['tokens', 'jwt']`.

I've also pushed an [example](https://github.com/simov/grant/tree/master/examples/limit-response) where I'm demonstrating how easy it is to decode the `id_token` yourself.
