### ISSUE TITLE
Maintain using lerna

### ISSUE THREAD

**Issue by ekoeryanto** [simov/grant#102]
Hi, I just want to suggest to using lerna to maintain this great repo.
suggested packages structure is
- packages/core
- packages/express
- packages/another
- ....

also i suggest to using scoped npm package
- @grant/core
- @grant/express
- @grant/another
- ....

THanks

**Comment by simov** [comment]
Hi @ekoeryanto,

The files you've mentioned were never meant to be distributed as separate modules, grant *is* the module.

Can you elaborate on the benefits of the approach you are proposing?

**Comment by ekoeryanto** [comment]
I'll explain that in a PR this week :pray: , for now I'm going to close this.
