### ISSUE TITLE
Does grant support token authentication ?

### ISSUE THREAD

**Issue by Igor-Lopes** [simov/grant#104]
Does grant support token authentication ? This is the use case of mobile apps, instead of doing redirections following the regular authentication flow of OAuth2 Web apps, the middleware would only process the access token sent in the request.

**Comment by simov** [comment]
Hi @Igor-Lopes,

No, Grant is only concerned with the _Wep App_ flow of OAuth 2.0 and with OAuth 1.0a

For the other types of login flows, available in OAuth 2.0, you don't really need a middleware that handles redirects and persists state. You can implement it yourself pretty easily.

**Comment by Igor-Lopes** [comment]
Hi @simov ,

Thanks for your reply !
