### ISSUE TITLE
Self signed certificates

### ISSUE THREAD

**Issue by RomanMinkin** [simov/grant#106]
Trying to use this library with the OAuth2.0/IODC server hosted with self signed certificate and getting this error on callback/verify call
```
error=unable%20to%20verify%20the%20first%20certificate
```

Is there a way to set something like `new https.Agent({rejectUnauthorized: false}` to the underlying request library?

Thank you in advance, pretty nice library btw!

**Comment by simov** [comment]
Does it work if you run the app with:

```bash
NODE_TLS_REJECT_UNAUTHORIZED=0 node app.js
```

Other than that the underlying HTTP client can be monkey-patched like this https://github.com/simov/grant/issues/93#issuecomment-445202851

Let me know if any of the above works for you.

**Comment by RomanMinkin** [comment]
@simov, yes, `NODE_TLS_REJECT_UNAUTHORIZED=0` works, but it does it for all the connection in the process :(
Monkey-patche also worksm with a little addition is that `grunt` must be required right after and not before the patch
```js
const request = require('grant/lib/client.js')
require.cache[require.resolve('grant/lib/client.js')].exports = (options) => {
  options.agent = new https.Agent({
    rejectUnauthorized: false,
  })
  return request(options)
}
const grant = require('grant-express')
```

Thank you for the quick replay!
