### ISSUE TITLE
Order of app.use(mount(grant)) and app.use(router(app))

### ISSUE THREAD

**Issue by bitinn** [simov/grant#11]
It seems if I do it in this order:

```
app.use(router(app));
app.use(mount(grant));
```

Then on my final callback, eg. `/handle_oauth_response` route, `ctx.params` is not populated.

If I do it in reversed order, eg.

```
app.use(mount(grant));
app.use(router(app));
```

Then things are fine, I can get `/login/:provider` as `ctx.params.provider`.

I haven't had the chance to look at it more closely, could be an incompatibility between `koa-router` v4 and v3 (I am using v4, grant-koa is on v3).

But I believe the final url is out of grant's scope right? Are they also reserved routes?

**Comment by simov** [comment]
I should probably switch to some routing module from the koajs org instead, as they are probably maintaining them together. Though if I can remember correctly koa-router was given as optional module for routing in the official router module in koajs org.

**Comment by bitinn** [comment]
`koa-router` is possibly the popular choice. Though I think the underlying solution is to make grant independent of specific routing system. eg. #10

**Comment by simov** [comment]
Closing in favor of https://github.com/simov/grant/issues/10
