### ISSUE TITLE
Samsite session cookie breaks twitter integration

### ISSUE THREAD

**Issue by mluggy** [simov/grant#111]
```
app.use(session({
      secret: 'foo',
      name: 'bar',
      cookie: {
        httpOnly: true,
        path: '/',
        secure: true,
        signed: true,
        sameSite: true
      },
      saveUninitialized: false,
      resave: false
    }))
```

yields this for twitter: **Grant: missing session or misconfigured provider**

Any specific reason?

**Comment by simov** [comment]
The cookie is not being set when you are redirected to the third-party web site to login. And therefore when you are redirected back to your web site the session is missing, because the cookie was never sent to the third-party server.
