### ISSUE TITLE
Linkedin Lite Profile Retrieval Process

### ISSUE THREAD

**Issue by sparzan** [simov/grant#114]
1) I'm receiving the following linkedin keys (which i slightly obfuscated). anyone knows what's the next path/graph call to retrieve the user's id, name and/or email? i tried linkedin/microsoft documentation and either refered to v1 or receiving invalid access_token.
```
{ access_token: 'e2cb93f6-1d81-4d1d-9836-xxxxxxxxxxx',
  access_secret: '80c94533-e3fe-49a5-be2f-xxxxxxxxxxx',
  raw:
   { oauth_token: 'e2cb93f6-1d81-4d1d-9836-xxxxxxxxxxx',
     oauth_token_secret: '80c94533-e3fe-49a5-be2f-xxxxxxxxxxx',
     oauth_expires_in: '5183999',
     oauth_authorization_expires_in: '5183999' } }
````
2) when requesting for this scope ['r_liteprofile', 'r_emailaddress'], grant still requests for the basic (bigger) profile. can there be a problem?

**Comment by simov** [comment]
Try this endpoint `https://api.linkedin.com/v1/people/~`. You have to use HTTP client that supports OAuth 1.0a.

**Comment by sparzan** [comment]
1. arrrg, xml on v1 :) and it says "This resource is no longer available under v1 APIs"
2. any idea?

**Comment by simov** [comment]
Actually no, I haven't used the LinkedIn's API in a long time. Note that they also support OAuth 2.0, and for that you have to use `linkedin2` in Grant for configuration key, and then `/connect/linkedin2` to login.
