### ISSUE TITLE
Aweber Integration

### ISSUE THREAD

**Issue by binarymee** [simov/grant#115]
I am planning to use **grant** as middleware for all the integrations in my application. I was trying out basic OAuth 2 flow and a sample integration with Salesforce. It worked like a charm. I started facing issues when I wanted to integrate [Aweber](https://api.aweber.com/) using grant.  It uses OAuth 1.0a. 
Till step2, I am not facing any issues. On Step 3 where the grant is making a [post request](https://github.com/simov/grant/blob/master/lib/flow/oauth1.js#L120) to access URL, my response is empty. I didn't get an access token and access secret.     

I am using `hapi 16`, `grant-hapi 4.5.0` and `yar 8.1.2`.

My configuration for Aweber
```
{
  "config": {
    "defaults": {
      "protocol": "https",
      "host": "localhost",
      "transport": "session",
      "state": true
    },
    "aweber": {
      "request_url": "https://auth.aweber.com/1.0/oauth/request_token",
      "authorize_url": "https://auth.aweber.com/1.0/oauth/authorize",
      "access_url": "https://auth.aweber.com/1.0/oauth/access_token'",
      "oauth": 1,
      "key": "<KEY>",
      "secret": "<SECRET>",
      "callback": "/integrations/aweber/callback"
    }
  }
}
```

I am getting empty raw body.

**Comment by binarymee** [comment]
I had a breakpoint before the request is made with `request-compose` and got the headers and tried in postman. 

I got the following response from Aweber.

```
{
  "error": {
    "status": 401,
    "documentation_url": "https://labs.aweber.com/docs/troubleshooting#unauthorized",
    "message": "Invalid signature. Expected signature base string: POST&https%3A%2F%2Fauth.aweber.com%2F1.0%2Foauth%2Faccess_token&oauth_consumer_key%<HIDDEN>%26oauth_nonce%3Deaca3eee4229491a934e12dba9651735%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1554540092%26oauth_token%<HIDDEN>%26oauth_verifier%<HIDDEN%26oauth_version%3D1.0 https://labs.aweber.com/docs/troubleshooting#unauthorized",
    "type": "UnauthorizedError"
  }
}
```

So it is clear that the signature generated by [oauth-sign](https://github.com/request/oauth-sign/blob/master/index.js#L79) is not matching what is expected in Aweber.
I used another library [OAuth1.0a](https://github.com/ddo/oauth-1.0a#readme) for testing purposes and was successfully able to pass through the third step. The way I used was

```
const OAuth = require('oauth-1.0a');
const crypto = require('crypto');

const hash_function_sha1 = (base_string, key) => {
  return crypto.createHmac('sha1', key).update(base_string).digest('base64');
};
    
const header = OAuth({
  consumer: { key: KEY, secret: SECRET },
  signature_method: 'HMAC-SHA1',
  hash_function: hash_function_sha1
});
```

[This is the way](https://github.com/ddo/oauth-1.0a/blob/master/oauth-1.0a.js#L124) signature is computed there. I couldn't find much difference in oauth-sign as well. 

Another issue is, for some reason, body is empty. The error is not captured by `request-compose`.

Any help would be appreciated. I would really like to make `grant` work in my application since it might help me to get rid of OAuth nuances for all third party integrations.

**Comment by simov** [comment]
Hi @binarymee, thanks for the detailed report! 

Well, I can't register on aweber.com without giving my credit card number, and I have a policy for myself to not register on such services just to test their OAuth flow.

Anyway, just by looking at their docs it seems that they are using non-standard OAuth parameters in the the third request: `resource_owner_key` and `resource_owner_secret`. As you can see [here](https://github.com/simov/grant/blob/v4.5.0/lib/flow/oauth1.js#L93-L94) there are no such parameters passed.

And so this might be a case of _custom_ a provider. All providers that differ in a way from the spec are in a sense documented in that file above.

And since you already have an OAuth app for aweber, can you try the following: add this snippet somewhere below `var options`:

```js
if (provider.aweber) {
  options.resource_owner_key = options.token
  options.resource_owner_secret = options.secret
  delete options.token
  delete options.secret
}
```

and let me know if that works. If that's the case then I'll add it + a test, and this provider will be officially supported after that.

**Comment by binarymee** [comment]
Hi @simov , Thank for getting back to me. 
I added the following configuration and tried. 
```
if (provider.aweber) {
  options.oauth.resource_owner_key = options.oauth.token
  options.oauth.resource_owner_secret = options.oauth.token_secret
  delete options.oauth.token
  delete options.oauth.secret
}
```

It didn't work. I got an empty response again. In their documentation, they have given examples based on [this python library](https://github.com/requests/requests-oauthlib). I guess they have named keys for `token` and `token_secret` to   `resource_owner_key` and `resource_owner_secret` respectively.

On debugging further, I can see that we are sending the token details and signature as part of the header, since it is default `transport_method` in the request.

```
OAuth oauth_consumer_key="<KEY>",oauth_nonce="eaca3eee4229491a934e12dba9651735",oauth_signature_method="HMAC-SHA1",oauth_timestamp="1554540092",oauth_token="<TOKEN>",oauth_verifier="<VERIFIER>",oauth_version="1.0",oauth_signature="<SIGNATURE>"
```

As I mentioned earlier, I have a working version with the library `OAuth1.0a` and it is also sending as part of the header, the same information
 
```
OAuth oauth_consumer_key="<KEY>",oauth_nonce="eaca3eee4229491a934e12dba9651735",oauth_signature="<SIGNATURE>",oauth_signature_method="HMAC-SHA1",oauth_timestamp="1554540092",oauth_token="<TOKEN>",oauth_verifier="<VERIFIER>",oauth_version="1.0"
```

The only difference I found is the order change in `oauth_signature`. I am sure that doesn't matter.

So I kind of suspect that the signature computation has some issues. Because if I use the same information and make a regular curl call I am getting the invalid signature error message.

**Comment by simov** [comment]
Without proper way for me to test it, it will be really hard for me to figure out what's the problem. I guess it's something small, because oauth-sign is used in request (the module), and also request-oauth is extracted from there too. You can also check out all of the providers in Grant that are tested and work without a problem with this setup (currently 28 in total).

**Comment by binarymee** [comment]
Aweber has release OAuth 2 flow now. The following custom configuration works
```
"aweber": {
        "authorize_url": "https://auth.aweber.com/oauth2/authorize",
        "access_url": "https://auth.aweber.com/oauth2/token",
        "oauth": 2,
        "key": "<KEY>",
        "secret": "<SECRET>",
        "scope": ["account.read list.read subscriber.read subscriber.write subscriber.read-extended"], 
        "callback": "/integrations/aweber/callback",
      }
```

**Comment by simov** [comment]
Thanks @binarymee I'll add it in the next release :+1:
