### ISSUE TITLE
Azure AD B2C integration

### ISSUE THREAD

**Issue by flyboarder** [simov/grant#120]
Would be great if we could use grant with AAD and AAD B2C

**Comment by simov** [comment]
Just by looking at the docs ([oauth2](https://docs.microsoft.com/en-in/azure/active-directory-b2c/active-directory-b2c-reference-oauth-code) and [openid](https://docs.microsoft.com/en-in/azure/active-directory-b2c/active-directory-b2c-reference-oidc)) it seems that it should be totally possible.

Though for some reason I wasn't able to login using the recommended URLs:

```
https://{tenant}.b2clogin.com/{tenant}.onmicrosoft.com/oauth2/v2.0/authorize
https://{tenant}.b2clogin.com/{tenant}.onmicrosoft.com/oauth2/v2.0/token
```

I tried with the following configuration:

```json
"azure": {
  "authorize_url": "https://{tenant}.b2clogin.com/{tenant}.onmicrosoft.com/oauth2/v2.0/authorize",
  "access_url": "https://{tenant}.b2clogin.com/{tenant}.onmicrosoft.com/oauth2/v2.0/token",
  "oauth": 2,
  "scope_delimiter": " ",
  "custom_params": {
    "p": "B2C_1_{flow}",
    "response_mode": "query"
  },
  "scope": {
    "{some-scope}",
    "offline_access"
  },
  "state": true,
  "key": "{client_id}",
  "secret": "{client_secret}"
}
```

I'm creating a provider in Grant called `azure`, but you can call it anyway you want. Then you have to set your tenant, flow, app credentials, scopes and so on. In the end you have to navigate to `/connect/azure` to login.

But all I'm getting with the above configuration is: `404 - File or directory not found.`

Then I decided to try the regular `microsoft` provider found in Grant:

```json
"microsoft": {
  "authorize_url": "https://login.microsoftonline.com/{tenant}/oauth2/v2.0/authorize",
  "access_url": "https://login.microsoftonline.com/{tenant}/oauth2/v2.0/token",
  "scope": [
    "openid"
  ],
  "state": true,
  "nonce": true,
  "key": "{client_id}",
  "secret": "{client_secret}"
}
```

with either specifying my tenant UUID or the `{name}.onmicrosoft.com`, and it works in both cases.

In case you don't specify `authorize_url` and `access_url` explicitly Grant defaults to the default URLs, meaning the `common` tenant.

Let me know if that works for you.

**Comment by flyboarder** [comment]
@simov Attempting to get this working again, I am able to authenticate but I also get a 404 error regarding the user profile. Seems we need a `profile_url` and im not sure what this would be for azure ad b2c with azure ad graph api.

**Comment by flyboarder** [comment]
I have been able to confirm that the `req.session.grant.response` contains an `error` however the error body is my valid request data.

I have been unable to find anywhere in grant code that returns an error with data.

**Comment by flyboarder** [comment]
@simov I am still unable to get this working, using the `microsoft` provider as you suggested does not work with the Azure AD B2C.

**Comment by simov** [comment]
I haven't had the chance to look at it again. 

Just to confirm, you are able to retrieve the access token, but not able to get the user's profile, is that correct?

**Comment by flyboarder** [comment]
I don't believe I can fully say that, I am able to get a token with this
```
"custom_params": {
          "response_mode": "query",
          "response_type": "token id_token"}
```
However with the following I get an invalid_grant error.
```
"custom_params": {
          "response_mode": "query",
          "response_type": "code id_token"}
```

More than willing to host some test infrastructure on Azure to get this working!

**Comment by flyboarder** [comment]
@simov 
Here is my current config for reference:
```
"azureb2c": {
        "authorize_url": "https://login.microsoftonline.com/{tenant}.onmicrosoft.com/oauth2/v2.0/authorize",
        "access_url": "https://login.microsoftonline.com/{tenant}.onmicrosoft.com/oauth2/v2.0/token",
        "profile_url": "https://graph.windows.net/me?api-version=1.6",
        "oauth": 2,
        "scope_delimiter": " ",
        "custom_params": {
          "p": "B2C_1_SignIn",
          "response_mode": "query",
          "response_type": "code id_token",
          "grant_type": "authorization_code"
        },
        "scope": [
          "https://{tenant}.onmicrosoft.com/dev/user_impersonation",
          "openid",
          "offline_access"
        ],
        "nonce": true,
        "state": true,
        "key": "AAD_CLIENT_ID",
        "secret": "AAD_CLIENT_SECRET"
      }
```

**Comment by flyboarder** [comment]
Closing as I was able to get a token, I have learned that the token returned by Azure AD B2C cannot be used to access the graph api's (AzureAD Graph/Microsoft Graph). As such you need to use alternate methods of retrieving the user profile data.

**Comment by simov** [comment]
Great! I was thinking about the same, so it makes sense. But can you share what is this other method to retrieve the user profile data in the case of AzureAD?

**Comment by flyboarder** [comment]
You are able to register an Azure AD Application (not B2C application) on the Azure AD B2C directory that can access the graph api.
https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-devquickstarts-graph-dotnet#build-user-crud-operations-by-using-the-graph-api

For our use case, we skip grant-profile and pass the data in claims.
