### ISSUE TITLE
Fastify integration

### ISSUE THREAD

**Issue by millette** [simov/grant#123]
[Fastify](https://github.com/fastify/fastify) has almost 11,000 stars on github, over 50,000 weekly downloads, is depended upon by 240 packages and claims to be [very fast](https://github.com/fastify/fastify#benchmarks).

I'd like to see it supported, hopefully pitch in.

Perhaps we could envisage splitting up the modules (grant and grant-profile) according consumers, but that would be a breaking change, and topic for another issue. Let me know if I should open that too.

**Comment by simov** [comment]
Fastify support would be great. 

The design decision made to keep all consumers in one place, was to make the syncing between different implementations easier. In the end they all have behave the same. Also note that the consumers are very simple middlewares that also doesn't interfere with each other in the module as a whole.

So I don't see a problem with adding more consumers here. Probably the consumer tests will be a bit hard to work with, but that will also be a good excuse for me to refactor them.

**Comment by millette** [comment]
I'll take a stab at fastify integration over the week-end if no-one beats me to it :-)

**Comment by Banonevar** [comment]
+1 to fastify

**Comment by simov** [comment]
> I'll take a stab at fastify integration over the week-end if no-one beats me to it :-)

Just don't bother adding all of the consumer tests as this will make reviewing it really hard for me. A single test somewhere will be just fine. Pick the easiest place, I can add the rest of the tests myself.

Also separate commit for the middleware itself will be nice, in case I decide to pick that, but not something else. 

Thanks :+1:

**Comment by ALITHEALI** [comment]
Any update on this one?

**Comment by millette** [comment]
@ALITHEALI no, sorry. I'm temporarily "retired". Feel free to pick it up, thanks.

**Comment by JaneJeon** [comment]
Update: fastify v3 is out, and with it brings support for (req, res, next) middlewares. So I'm pretty sure https://github.com/simov/grant/blob/master/lib/handler/express-4.js#L19 this could work outright for fastify now.

**Comment by simov** [comment]
Interesting, I'll definitely look into that :+1:

**Comment by JaneJeon** [comment]
@simov btw just wanted to tell you I appreciate all the work you put into this!

**Comment by delaneyj** [comment]
@simov I am also highly interested in this integration.  I noticed the [npm registry entry](https://www.npmjs.com/package/grant-fastify) but with no content and pointing at v5.3.0 which doesn't seem to have tags in github.  Also when I tried to use `fastify-express` and the express middleware I get 
```bash
(node:12657) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'headersSent' of undefined
    at headersSent (../node_modules/finalhandler/index.js:256:21)
    at ../node_modules/finalhandler/index.js:92:17
    at ../node_modules/express/lib/router/index.js:635:15
    at next (../node_modules/express/lib/router/index.js:210:14)
    at Function.handle (../node_modules/express/lib/router/index.js:174:3)
    at Function.handle (../node_modules/express/lib/application.js:174:10)
```  
which I'm not sure if its a grant issue or fastify-express.  I am using `fastify-secure-session`.  Does it have to be `express-session` to work?

Would love to know where support is at and what can be done to help.

**Comment by simov** [comment]
@delaneyj I published all those names to reduce potential confusion in future, but as it turns out I confused people instead ..

So there will be a Fastify handler for Grant, and I wasn't sure if I'll be able to do it in the next release v5.3.0 or not. Now it seems most likely to land in v5.4.0 instead.

Also note that the grant-* handler modules doesn't serve any purpose other than looking nicer in your package.json file probably. All handlers are [available directly](https://github.com/simov/grant#misc-handler-constructors) in Grant.

As for `fastify-express`, I don't know, and you have to ask the owners of that package.

**Comment by calvinl** [comment]
@simov thank you for your hard work with this package? Just wanted to ask if you have an estimate for 5.4.0 with fastify handlers? Really looking forward to that :) Happy to help test out also.

**Comment by simov** [comment]
Hi @calvinl, thanks for your interest. It's scheduled for the end of next month at most, meaning end of September, but it can be earlier than that too. Note that I'm planning to support the latest Fastify major only.

**Comment by calvinl** [comment]
@simov thats awesome, thank you! Please let me know if I can pitch in in any way.

**Comment by simov** [comment]
The Fastify handler for Grant is ready, though you still have to wait a little bit more before its official release.

So in the meantime you can add it to your `package.json` like this:

```json
"grant": "github:simov/grant"
```

And then you register it as a regular plugin:

```js
var fastify = require('fastify')
var cookie = require('fastify-cookie')
var session = require('fastify-session')
var grant = require('grant').fastify()

fastify()
  .register(cookie)
  .register(session, {secret: '01234567890123456789012345678912', cookie: {secure: false}})
  .register(grant(require('./config')))
  .route({method: 'GET', path: '/hello', handler: async (req, res) => {
    res.send(JSON.stringify(req.session.grant.response, null, 2))
  }})
  .route({method: 'GET', path: '/hi', handler: async (req, res) => {
    res.send(JSON.stringify(req.session.grant.response, null, 2))
  }})
  .listen(3000)
```

You can see all the relevant examples here:

- [handler-fastify](https://github.com/simov/grant/blob/master/examples/handler-fastify/fastify-session.js)
- [transport-state](https://github.com/simov/grant/blob/master/examples/transport-state/fastify.js)
- [dynamic-state](https://github.com/simov/grant/blob/master/examples/dynamic-state/fastify.js)

Let me know what you think.

**Comment by simov** [comment]
Change in plans again, decided to release v5.4.0 today :tada: 

Initially I was planning to include some other stuff in this release but as it turned out that's going to require a bit more research on my end, so no point in holding the Fastify handler back.

Thanks for your patience :+1:
