### ISSUE TITLE
cookie-session instead of express-session ? 

### ISSUE THREAD

**Issue by max-l** [simov/grant#124]
It seems that grant requires express-session, 

I want to use cookie-session:  https://github.com/expressjs/cookie-session

It seems that I could follow this example: 
  https://github.com/simov/grant/blob/master/examples/jwt/app.js

destroy the express-cookie when it is created, and replace it with a cookie-session, but the problem is that cookie-session also uses req.session to expose session data to route handlers.

Could express-session be decoupled from grant by providing a few callbacks ?

**Comment by simov** [comment]
Fixed in https://github.com/simov/grant/commit/d39902b43520d5f67db1f74b451b8b897c92e7b5
