### ISSUE TITLE
dependency on core-js

### ISSUE THREAD

**Issue by AaronNGray** [simov/grant#131]
This should not be encouraged core-js is a very bad polyfill library that is bloatware both in its builder and also in generated code.

```
> core-js@2.6.9 postinstall C:\Users\aaron\GitHub\grant\node_modules\core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
```

**Comment by simov** [comment]
No idea which dependency is using core-js TBH. I guess that's used by some of the build modules, then that affects only the backward compatibility that I still have for node 4 and 6, which I'm going to drop off soon anyway.
