### ISSUE TITLE
Issue with Grant and hapi session management with multiple apps

### ISSUE THREAD

**Issue by binarymee** [simov/grant#135]
I am using grant extensively in my hapi 16 application.
We have an Apps and Integration page and I am using the grant to connect to all the third parties listed there.
I have a critical issue with session management in the grant. 

My callback URL route is 

```
{
  method: ['GET'],
  path: '/integrations/{provider}/callback',
  config: {
    auth: {
      mode: 'required',
      strategy: 'connect'
    },
    handler: connectIntegration
  }
}
```
In my strategy `connect`, I have done 

```
const payload = request.yar.get('grant');
if (!payload.dynamic) {
  throw new Error('Dynamic grant overrides are not set while authenticating the integration');
}
``` 

I use `dynamic` to send important information back to the application like the ID of the third party I am integrating and some other meta info. 

The problem is, it was working fine till I had just one app. The moment I started adding more apps, I started seeing a critical issue.

`dynamic` details of an app I connected earlier were sent while connecting some other app. This is a very critical issue for me which is totally unexpected. Initially, I was having some doubts about my implementation and finally figured out there is something to do with `yar` session management.

On digging deeper from the answer provided by you [here](https://github.com/simov/grant/issues/41) I added 
```
request.yar.reset(); //Clearing of the session once the handshake is done https://github.com/simov/grant/issues/41#issuecomment-163873802
```

After this, I am not able to reproduce the issue I talked about. But I have stumbled upon another problem. Frequently `request.yar.get('grant')` gives me `undefined` in my strategy which stops the callback from executing.

What could be the root cause of this problem? How it can be solved elegantly?

**Comment by simov** [comment]
Where exactly do you call `request.yar.reset()`, and where `request.yar.get('grant')` is returning `undedined`?

**Comment by binarymee** [comment]
`request.yar.get('grant')` is called while hitting the callback URL and `request.yar.reset()` is called after the callback has been processed.

**Comment by binarymee** [comment]
@simov , We have multiple environments where we test the applications. This issue I am seeing only in one environment.
The difference in that environment with the others are multiple instances are running. So OAuth steps the initial one can go to one instance and final callback can be triggered to other. By any chance, this could be the reason?

**Comment by simov** [comment]
I'm not sure I understand the topology of your infrastructure. Multiple instances of what? Hapi? Grant? Can you explain your setup in more details?

**Comment by binarymee** [comment]
That was my bad. I mean, multiple servers(EC2 instances) will process the request made by the client. In the OAuth flow, the initial request can go to `Server1` and the callback can be triggered on `Server2`.

**Comment by simov** [comment]
Do you use an external session storage, like [some of these](https://github.com/simov/grant/tree/master/examples/hapi-session-stores)?

**Comment by binarymee** [comment]
I don't. Should be the reason.
I was under the wrong assumption that the session management happens with the cookie stored in the browser. If yar relies on the server to store and retrieve without a common store, that could trigger this problem.

**Comment by binarymee** [comment]
Thanks for the help @simov!

**Comment by simov** [comment]
I'm seeing 3 options here:

1. Setup an external session store
2. Sent the entire session with the cookie - there have to be an option for that, just make sure you are not encoding sensitive data in that cookie! Also cookies have size limits on some servers.
3. Run Grant in a separate micro instance in your private network. When a user makes request to your app server, redirect it to the Grant server by passing the required dynamic data in the querystring, then the Grant instance will handle the redirects during the OAuth flow using the in-memory session store, lastly in the final callback you have to redirect the user to your app server, again using querystring to encode the needed data.

**Comment by simov** [comment]
The last chapter in [this article](https://dev.to/simov/oauth-like-a-boss-2m3b) explains exactly that scenario.

**Comment by binarymee** [comment]
External session store looks much elegant and cleaner. I will be going with that :)
