### ISSUE TITLE
specifying the /oauth/<provider>/callback

### ISSUE THREAD

**Issue by edwardsmarkf** [simov/grant#141]
hello - first off, thank you for providing a uniform way to use node and oauth.

i am able to get the facebook connection working using localhost very simply.  however, when i try to go through an apache proxy, i continue to get "http://localhost/oauth/facebook/callback" embedded in the URL (below).  so, i am thinking there is some extra grant parameter to manually specifiy this URL callback value rather than relying on a default.  

so far i have tried "callback" and "redirect" but neither appear to do anything.

suggestions?

[`"callback": "/hello"](https://www.npmjs.com/package/grant)
`

my callback:
https://www.facebook.com/login.php?skip_api_login=1&api_key=2302318070030832&kid_directed_site=0&app_id=2302318070030832&signed_next=1&next=https%3A%2F%2Fwww.facebook.com%2Fdialog%2Foauth%3Fclient_id%3D2302318070030832%26response_type%3Dcode%26redirect_uri%3Dhttp%253A%252F%252Flocalhost%253A3030%252Foauth%252Ffacebook%252Fcallback%26ret%3Dlogin%26fbapp_pres%3D0%26logger_id%3Df7c24ab0-6d74-4291-ba49-f78e439ab90a&cancel_url=http%3A%2F%2Flocalhost%3A3030%2Foauth%2Ffacebook%2Fcallback%3Ferror%3Daccess_denied%26error_code%3D200%26error_description%3DPermissions%2Berror%26error_reason%3Duser_denied%23_%3D_&display=page&locale=en_US

EDIT:

including something like this seems to help:

        "defaults" : {
                "protocol" : "https",
                "host" : "MYDOMAIN.COM/oauth/facebook/callback"
        },

**Comment by simov** [comment]
What is your Grant config exactly?

**Comment by edwardsmarkf** [comment]
hi - thank you for answering me.  i am using feathersJs.   and this seemed
to work fine:

    "oauth": {
         "defaults" : {
                "protocol" : "https",
                "host" : "featherstest.website"
        },
      "facebook": {
        "key": "2XXXXXXXXXXXX7",
        "secret": "dXXXXXXXXXXXXXXXXXXXd"

however, i am wondering if there is any way the "defaults" could be
embedded inside the facebook tag?   reason i am asking is that i hope to
include several oauth calls, and i dont know of the others
(google/msn/github) will object to having a protocol and port set, since
they all currently work just using the defaults.


Thank you,

Mark Edwards

**Comment by simov** [comment]
@edwardsmarkf the `defaults` key is there only for convenience. Any option specified in it can be overriden in the providers below. Check out the [docs](https://github.com/simov/grant#configuration-scopes) about it.
