### ISSUE TITLE
Feature request: add LINE support

### ISSUE THREAD

**Issue by JaneJeon** [simov/grant#142]
Hi, first of all, love the library!

But as I was looking thru the list of identity providers, I noticed that LINE isn't there. While I'm sure nobody uses line outside of Japan, it's super duper popular there and I thought it would warrant inclusion.

Thank you

**Comment by simov** [comment]
Sounds good, never heard of [line.me](https://developers.line.biz/en/docs/line-login/web/integrate-line-login/) before, I'll have a look.

**Comment by simov** [comment]
Added here https://github.com/simov/grant/commit/d3e261e284b5b1523196b0c1d652fac53d27c637 Let me know if it works for you.
