### ISSUE TITLE
Grant and ReverseProxy using an extra path element

### ISSUE THREAD

**Issue by edwardsmarkf** [simov/grant#144]
I have much success combining google and FB oauth into a single node script over ReverseProxy!  😁 
However, when I attempt to insert another "pathname" into the proxy, the callback fails.  in other words, when I am using `https://domain.com/GRANT/` everything appears to work just fine in the proxy, both google and FB allow me to successfully log in.   

But in the callback, I get back this:
 `The requested URL /oauth/connect/google/callback was not found on this server.`  
Somehow the `/GRANT/` pathname is getting lost, both on FB and Google, since it should be "/GRANT/connect/google/callback".  is there a config setting I am missing?  I have tried using the "path" element as well, but when I try setting that, I am no longer able to even access either FB or google, i get back "404 page not found"

```
    "oauth": {
        "redirect" : "/",
         "defaults" : {
                "protocol" : "https",
                "host" : "featherstest.website/feathers",
                "path" : "/feathers"    /* this seems to cause more problems for me */
        },
      "facebook": {
        "key": "5XXXXXXXXXXXXXXXX4",
        "secret": "7XXXXXXXXXXXX8a",
        "scope": ["public_profile, email"]
      },
      "google": {
        "key": "81XXXXXXXXXXXXXdi.apps.googleusercontent.com",
        "secret": "XI2XXXXXXXXXXXXXXXMi",
        "scope": [
          "email",
          "profile",
          "openid"
        ]
      }
    }
```
any suggestions?

**Comment by simov** [comment]
You have to specify that path prefix in the redirect_url of your OAuth app (on the Google's and Facebook's app configuration page):

```
https://mywebsite.com/grant/connect/google/callback
https://mywebsite.com/grant/connect/facebook/callback
```

Then in your Grant config you have to specify `path: '/grant'` as well. 

The `path` option is used for generating the `redirect_uri` that's being sent during the authorization step. You can read more about it [here](https://github.com/simov/grant#redirect-url) and [here](https://github.com/simov/grant#redirect-uri).

**Comment by edwardsmarkf** [comment]
hello - i did that, otherwise both FB and google would give an error
message, since the specified callback has to match exactly (even the
trailing path slash).   would it be possible to send you a couple of
screenshots?  i feel as if i am very close to getting this resolved.

note:  i am hoping to run multiple node-oauth servers using different
ports, and thought using ProxyReverse with a pathname was the best solution.

Thank you,

Mark Edwards

**Comment by simov** [comment]
Depending on your proxy configuration you might have to prefix your [middleware](https://github.com/simov/grant#path-prefix) as well.

**Comment by edwardsmarkf** [comment]
hi -

sorry i am a bit confused.   but first off, THANK YOU for your assistance,
and a very special THANK YOU for creating and maintaining grant.  your
efforts are truly appreciated.

the apache proxy is very simple:

  <Location /grant/>
    ProxyPass http://localhost:3030/
    ProxyPassReverse http://localhost:3030/
  </Location>


here is the link i am being redirected to:

FB:  ( i go to  https://mydomain.com/grant/oauth/connect/facebook)

https://www.facebook.com/login.php?skip_api_login=1&api_key=526098801527394&kid_directed_site=0&app_id=526098801527394&signed_next=1&next=https%3A%2F%2Fwww.facebook.com%2Fdialog%2Foauth%3Fclient_id%3D526098801527394%26response_type%3Dcode%26redirect_uri%3Dhttps%253A%252F%252Fmydomain.com%252Fgrant%252Foauth%252Ffacebook%252Fcallback%26scope%3Dpublic_profile%252C%2Bemail%26ret%3Dlogin%26fbapp_pres%3D0%26logger_id%3Da0c87b91-4636-4b1b-8957-2f14d5f12e96&cancel_url=https%3A%2F%2Fmydomain.com%2Fgrant%2Foauth%2Ffacebook%2Fcallback%3Ferror%3Daccess_denied%26error_code%3D200%26error_description%3DPermissions%2Berror%26error_reason%3Duser_denied%23_%3D_&display=page&locale=en_US

and so i am seeing the URL:
redirect_uri%3Dhttps%253A%252F%252Fmydomain.com%252Fgrant%252Foauth%252Ffacebook%252Fcallback

--or--

 redirect_uri=https://mydomain.com/grant/oauth/facebook/callback

and yet this is the link i am returning to for facebook

https://mydomain.com/oauth/connect/facebook/callback?code=AQD-PTVSdfr2gPYBspHScLQbhMBTNV2Z2NOLjZ5BxSujsYsJZEwE1_ASAIQS_f4yaq5Lzmxelz-Ff6BJvnQXTJ5I1weD2P3GR0Fex6jiBzTZgfSWtoZU7KyXxLxmimUu4SMz5oJHZOWwcxfSMpImTPL4FK_6Bzo2Kl85bFgJAKjOAVLG5bKQd23wZMbMzrMkO_MHigNcFXEPOucse8z_GaIrnuX08qg94J3P__rsXtQxjUFLnBtS4KQ_OTRHcEYGS6oMl68njzrtB3mE2rXU2UJXBZ_1KavFSbs8v5Pk21j8qdFtgnNXz77eU50j3Hoj7xabnLrXNMdf9nf0dtFYSjl1#_=_


for whatever reason, '/grant/' is not coming through.

so somewhere (middleware?) it appears the "Valid OAuth Redirect URIs"  of  "
https://mydomain.com/grant/oauth/facebook/callback" is being converted to
just "/oauth/connect/facebook/callback" and dropping the /grant/ path.

The requested URL /oauth/connect/facebook/callback was not found on this
server.

could you please recommend which script i might look at to see if this is a
"middleware" issue?     i am wondering if there is something i can/should
hard-code for now just to get past this issue.

and thank you again for any assistance and consideration.


Thank you,

Mark Edwards

**Comment by simov** [comment]
Paste your exact Grant configuration here (without credentials).

**Comment by edwardsmarkf** [comment]
"oauth": {
        "redirect" : "/",
         "defaults" : {
                "protocol" : "https",
                "host" : "featherstest.website/feathers"
        },
      "facebook": {
        "key": "52XXXXXXXXXXXXX94",
        "secret": "74XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX8a",
        "scope": ["public_profile, email"]
      },
      "google": {
        "key": "81XXXXXXXXXXXXXXXXXXXXdi.apps.googleusercontent.com",
        "secret": "XIXXXXXXXXXXXXXXXXXXXXXXXXMi",
        "scope": [
          "email",
          "profile",
          "openid"
        ]
      }
    }

Thank you,

Mark Edwards

**Comment by simov** [comment]
Set `path: '/grant'` inside `defaults`.

**Comment by edwardsmarkf** [comment]
like this?

        "defaults" : {
                "protocol" : "https",
                "host" : "featherstest.website",
               "path" : "/grant"
        },

 (sorry its late in the western USA but i am looking forward to getting
this working in the morning.....)

and once again, thank you very much.


Thank you,

Mark Edwards

**Comment by edwardsmarkf** [comment]
hi simov -

using:  https://featherstest.website/feathers/oauth/connect/facebook

         "defaults" : {
                "protocol" : "https",
                "host" : "featherstest.website/feathers"
        },

this calls:

https://www.facebook.com/login.php?skip_api_login=1&api_key=526098801527394&kid_directed_site=0&app_id=526098801527394&signed_next=1&next=https%3A%2F%2Fwww.facebook.com%2Fdialog%2Foauth%3Fclient_id%3D526098801527394%26response_type%3Dcode%26redirect_uri%3Dhttps%253A%252F%252Ffeatherstest.website%252Ffeathers%252Foauth%252Ffacebook%252Fcallback%26scope%3Dpublic_profile%252C%2Bemail%26ret%3Dlogin%26fbapp_pres%3D0%26logger_id%3D34cc4ba3-f083-4f70-815e-e69b9894d17b&cancel_url=https%3A%2F%2Ffeatherstest.website%2Ffeathers%2Foauth%2Ffacebook%2Fcallback%3Ferror%3Daccess_denied%26error_code%3D200%26error_description%3DPermissions%2Berror%26error_reason%3Duser_denied%23_%3D_&display=page&locale=en_US

but using:

        "defaults" : {
                "protocol" : "https",
                "host" : "featherstest.website",
                "path" : "/feathers"
                "path" : "/feathers/"   (tried both)
        },

returns:

404  Page Not Found


Thank you,

Mark Edwards

**Comment by simov** [comment]
So this have to be something related to Feathers then. Why don't you try with one of the existing examples [here](https://github.com/simov/grant/tree/master/examples) first? Pick one, configure it, put it behind your proxy, see if it works. I have Grant deployed behind Nginx, using a custom path prefix.

**Comment by edwardsmarkf** [comment]
very excellent suggestion!  thank you so much.

Thank you,

Mark Edwards

**Comment by edwardsmarkf** [comment]
just in case you are interested, your excellent idea worked perfectly using
`/grant/examples/basics` with

   defaults: {
      protocol: 'https',
      host: 'ccscares.services',
      path: '/grant'
    },

so thanks to your suggestion, we now know the issue is indeed with
feathers, and not with grant.


i have found something of a workaround that appears to work, using the new
path-name TWICE.  i plan on running this by the feathers-slack page, but at
least i found a workaround:


./var/httpd/conf/httpd.conf:

  <Location /feathers/>
    ProxyPass http://localhost:3030/
    ProxyPassReverse http://localhost:3030/
  </Location>


./config/default.json:

    "oauth": {
        "redirect" : "/feathers/",
         "defaults" : {
                "protocol" : "https",
                "path" : "/feathers/oauth"

        },
      "facebook": {
        "key": "5XXXXXXXXXXXXXXXXXXXX94",
        "secret": "74XXXXXXXXXXXXXXXXXXXXXXXX88a",
        "scope": ["public_profile, email"],
        "redirect_uri": "
https://DOMAIN.WEBSITE/feathers/feathers/oauth/connect/facebook/callback",
        "callback": "
https://DOMAIN.WEBSITE/feathers/feathers/oauth/facebook/authenticate"
      },
      "google": {
        "key": "
813XXXXXXXXXXXXXXXXXXXXXXXXXXXX4di.apps.googleusercontent.com",
        "secret": "XXXXXXXXXXXXXXXXXXXXXXXXXMi",
        "scope": [
          "email",
          "profile",
          "openid"
        ]
      }
    }


index.html:

  var socket = io( { transports: ['polling'], path: '/feathers/socket.io'
});
<a href='
https://featherstest.website/feathers/feathers/oauth/connect/facebook
'>facebook</a>

**Comment by simov** [comment]
That's definitely helpful :+1:

**Comment by edwardsmarkf** [comment]
bonus:  google worked right out of the box too!

Thank you,

Mark Edwards

**Comment by edwardsmarkf** [comment]
simov - i gave you a shout-out in my article:   [https://codeforgeek.com/implement-oauth2-using-auth0/](https://codeforgeek.com/implement-oauth2-using-auth0/)

**Comment by simov** [comment]
Thanks man! Auth0 is great too :)
