### ISSUE TITLE
patreon oauth

### ISSUE THREAD

**Issue by TimIsOverpowered** [simov/grant#151]
Patreon oauth requires an user-agent header now otherwise it will return IM NOT A ROBOT captcha test. [ref](https://www.patreondevelopers.com/t/cloudflare-im-not-a-robot-blocking-api/2607/7)

**Comment by simov** [comment]
Thanks for the heads-up, it should be an easy fix. I'll include it in the next release.

**Comment by simov** [comment]
The `user-agent` header is set now set on all internal requests in v4.7.0
