### ISSUE TITLE
Mailchimp as provider

### ISSUE THREAD

**Issue by parkerproject** [simov/grant#152]
As anyone successfully made grant work for Mailchimp as the provider?  I have tried everything possible but all I get is the `code`, it doesn't make the final call to get the `access_token`

**Comment by simov** [comment]
Most likely your redirect URL isn't correct. You have to set it to point back to your server. For example if your server is listening on `http://localhost:3000` then you can have the following configuration:

```js
{
  defaults: {protocol: 'http', host: 'localhost:3000', ...},
  mailchimp: {callback: '/hello', ...}
}
```

And then in Mailchimp's UI for your OAuth application you have to set the Redirect URL to be: `http://localhost:3000/connect/mailchimp/callback` this route is used internally by Grant. You will receive the response data inside the `/hello` route instead.

**Comment by parkerproject** [comment]
I see what my issue was, I used `localhost` in the config file whilst I use `127.0.0.1` in the Mailchimp redirect URI. Grant considers those to be 2 different URI

**Comment by parkerproject** [comment]
I reopened this because I notice `error=Grant%3A%20missing%20session%20or%20misconfigured%20provider` when I use subdomain as host:
```
{
  defaults: {protocol: 'https', host: 'subdomain.example.com', ...},
  mailchimp: {callback: '/hello', ...}
}
```

and Redirect URL to be: `http://subdomain.example.com/connect/mailchimp/callback` on OAuth UI

**Comment by simov** [comment]
Is your server reachable at `http://subdomain.example.com`? Also your `protocol` is set to `https`, but your redirect URL is using `http`.

**Comment by parkerproject** [comment]
Sorry that was a typo, my redirect protocol is “https”
My host is reachable at the subdomain, that was just an example

**Comment by simov** [comment]
That means something is wrong with your session. Can you also post your entire configuration, without sensitive data in it of course.

**Comment by parkerproject** [comment]
```
{
  "development": {
    "defaults": {
      "protocol": "http", 
      "host": "127.0.0.1:5000",
      "transport": "session"
    },
    "mailchimp": {
        "authorize_url": "https://login.mailchimp.com/oauth2/authorize",
        "access_uri": "https://login.mailchimp.com/oauth2/token",
        "oauth": 2,
        "callback": "/channel",
        "client_id": [client_id],
        "client_secret": [client_secret]
      }
  },
  "production": {
    "defaults": {
      "protocol": "https", 
      "host": "app.example.co",
      "transport": "session"
    },
    "mailchimp": {
        "authorize_url": "https://login.mailchimp.com/oauth2/authorize",
        "access_uri": "https://login.mailchimp.com/oauth2/token",
        "oauth": 2,
        "callback": "/channel",
        "client_id": [client_id],
        "client_secret": [client_secret]
      }
  }
}
```

redirect_url on Mailchimp App : `https://app.example.co/connect/mailchimp/callback`

express server:
```
.....
app.use(grant(config[process.env.NODE_ENV || 'development'])); 

app.use('/channel', (req, res) => {
 // should access the response here
})
....

**Comment by simov** [comment]
Which URL you are using to connect?

It have to be `https://app.example.co/connect/mailchimp`

**Comment by parkerproject** [comment]
`https://app.treck.co/connect/mailchimp`

**Comment by simov** [comment]
Can you show me the express, your session middleware, and grant version here, just copy/paste them from package.json

**Comment by parkerproject** [comment]
```
    "express": "^4.17.1",
    "express-session": "^1.17.0",
    "grant-express": "^4.7.0",
```

**Comment by simov** [comment]
Is your server by any chance behind a load balancer, meaning do you have multiple instances of your grant/express/app server running?

**Comment by parkerproject** [comment]
I'm using `pm2 cluster mode` could that be the issue. I'm also using Nginx proxy

**Comment by simov** [comment]
Yes, in this case you have to use external session store, because you are running multiple instances of your application and `express-session` is an in-memory session store. Have a look at the [express session store examples](https://github.com/simov/grant/tree/master/examples/express-session-stores), and also the list of [compatible session stores](https://www.npmjs.com/package/express-session#compatible-session-stores).

**Comment by parkerproject** [comment]
You are right, I just changed to `fork` mode in `pm2` and it worked. thanks for your help on this, I will check the other session stores
