### ISSUE TITLE
How to dynamically set host/callback?

### ISSUE THREAD

**Issue by homerjam** [simov/grant#155]
Hi, I'd like to dynamically set the host in the default config and the provider callback url on request. Is this possible?

Thanks

**Comment by simov** [comment]
The `protocol` and the `host` options are only used to generate the `redirect_uri` option, that is where your OAuth apps redirect users back to your server.

You can use a [Dynamic Override](https://github.com/simov/grant#dynamic-override) to set the `redirect_uri` dynamically.

**Comment by homerjam** [comment]
Ah, great. Thanks for your help, this library is super useful!
