### ISSUE TITLE
Support Fusionauth

### ISSUE THREAD

**Issue by rdewolff** [simov/grant#156]
Is there any plan to support FusionAuth ? 

C.f. : https://fusionauth.io

**Comment by simov** [comment]
Thanks for the feedback, never heard of them, I'll have a look.

**Comment by rdewolff** [comment]
Great, hope this will will turn out well :)

**Comment by simov** [comment]
:wave: can you check if that configuration works on your end:

```json
{
  "defaults": {
    "protocol": "http",
    "host": "localhost:3000"
  },
  "fusionauth": {
    "authorize_url": "http://localhost:3000/oauth2/authorize",
    "access_url": "http://localhost:3000/oauth2/token",
    "oauth": 2,
    "scope_delimiter": " ",

    "key": "APP_ID",
    "secret": "APP_SECRET",

    "state": true,
    "nonce": true,
    "pkce": true,
    "scope": [
      "openid",
      "offline_access"
    ],
    "custom_params": {
      "tenantId": "UUID"
    },

    "callback": "/hello"
  }
}
```

The `http://localhost:3000` is where your fusionauth server listens to, so you may have to update it. Then you have to set your app `key` and `secret` as well as the `tenantId`. The `/hello` callback is where you will receive the response data in your Grant client server.

Then all you need to do is to navigate to `http://localhost:3000/connect/fusionauth` to login.

Let me know if it works.

**Comment by simov** [comment]
Fusionauth was added to the list of officially supported providers. Let me know if it works for you :+1:
