### ISSUE TITLE
State/Nonce size is too small for Login.Gov

### ISSUE THREAD

**Issue by justinmeid** [simov/grant#158]
I am trying to setup [Strapi](https://github.com/strapi/strapi) with a new auth provider ([Login.gov](https://login.gov/)). They use grant for auth. The issue I am currently having is that Login.gov wants state and nonce to be at least 32 characters in length. I know this is probably an edge case but is there any reason this 10 couldn't be changed to 32? 

https://github.com/simov/grant/blob/c8e036d35d73de2344cc715bed076cc0a2315139/lib/config.js#L147

**Comment by simov** [comment]
No, this can be updated. Can you point me to the exact URL of the login.gov docs regarding this issue? Also are you sure that rule applies for both state and nonce, or just one or the other?

**Comment by justinmeid** [comment]
Sweet, thank you for the quick response! If you go [here](https://developers.login.gov/oidc/#authorization) and scroll down a little bit to state/nonce it appears that they both require "a unique value at least 32 characters in length"

**Comment by simov** [comment]
Thanks, I'll have a look at it. In the meantime you can pass both `state` and `nonce` as strings that are long enough in your configuration.

**Comment by simov** [comment]
Just read through the docs and as it seems the `pkce` flow should work with Grant. Here is an example config that you can try:

```js
{
  "defaults": {
    "protocol": "http",
    "host": "localhost:3000"
  },
  "logingov": {
    // or idp.int.identity.gov for the production version
    "authorize_url": "https://idp.int.identitysandbox.gov/openid_connect/authorize",
    "access_url": "https://idp.int.identitysandbox.gov/api/openid_connect/token",
    "oauth": 2,
    "scope_delimiter": " ",

    "pkce": true,

    // these should be generated dynamically, but just for the test:
    "state": "c5690fd2b875398e4e0ca83289eaac0739d35354",
    "nonce": "c5690fd2b875398e4e0ca83289eaac0739d35354",

    // set your credentials here
    "key": "app id",
    "secret": "app secret",

    // pick scopes
    "scope": [
      "openid", "address", "email", "phone"
    ],

    "custom_params": {
      // or http://idmanagement.gov/ns/assurance/loa/3
      "acr_values": "http://idmanagement.gov/ns/assurance/loa/1",
      "prompt": "select_account" // or login
    }
  }
}
```

The `defaults` is where your local server is listening to. That also reflect your `redirect_uri` that you have to set for your app: `http://localhost:3000/connect/logingov/callback`. To login just navigate to `http://localhost:3000/connect/logingov`. Let me know if that works.

As for the `private_key_jwt` flow, that won't work. If you can configure a sandbox app for it and send me the credentials needed on private (email) I can implement that quickly, then you can delete that app or whatever. Obviously I can't register as a developer on that site, and not having an actual example will take longer to implement and test properly.

**Comment by justinmeid** [comment]
Thanks so much for looking in to it! Following the steps above, I was easily able to get `pkce` working. After I got that working I went on and got `private_key_jwt` working. Check out [this repo/commit](https://github.com/justinmeid/strapi-logingov/commit/d4535b541bc9784061f85eba0daae40bb1f017af) if you are interested in seeing how its implemented. I used [openid-client](https://github.com/panva/node-openid-client) as a reference.

**Comment by simov** [comment]
Thanks! This is definitely going to help me implement this feature quicker here. I'm glad you got it working on your end. Lets keep this issue open for now, I'll let you know when these changes land here as I'm currently working on a larger refactoring of the code base.

**Comment by justinmeid** [comment]
Sounds good! Let me know if there is anything I can do to help :) I am new to contributing to open source but would to love to help where I can

**Comment by simov** [comment]
Hey @justinmeid, just released the support for `private_key_jwt` client authentication in v5.1.0

Now you can use the following options to control that feature:

- `token_endpoint_auth_method` - set it to `private_key_jwt`
- `token_endpoint_auth_signing_alg` - optional, defaults to `RS256`
- `private_key` - PEM string or JWK object used to sign the JWT
- `public_key` - optional, PEM string or JWK object, this is used to obtain the `x5t` key of your public key, this is only used as an alternative of the `kid` and depends on whether the provider expects that or not

The only example that I have so far is with the [`microsoft`](https://github.com/simov/grant/blob/master/examples/token-endpoint/config.json) provider.

Also added `logingov` to the list of supported providers, let me know if it works for you.
