### ISSUE TITLE
github login (with koa 2) not returning "access_token" via response bod; in 4.7.0 (works in 4.6.6)

### ISSUE THREAD

**Issue by insidewhy** [simov/grant#159]
Using koa. In `4.6.6` I can get `const authData = querystring.parse(ctxt.response.body)` and `authData` has the `access_token` I need. With `4.7.0` I see that `ctxt.response.body` is now `undefined` instead of the object that was returned with `4.6.6`.

**Comment by insidewhy** [comment]
With 4.7.0 it seems I can get the access_token via `ctxt.session!.grant.response.access_token`.

Maybe I was supposed to be doing this all along?

**Comment by simov** [comment]
This is controlled by the `transport` options. You probably now have `transport: 'session'` set. If omitted `transport` defaults to `querystring`, meaning you either receive the response data in the session object or in the querysting.

**Comment by insidewhy** [comment]
@simov There were no code changes, only an upgrade from `4.6.6` to `4.7.0`, but I did always have `transport: 'session'` set, yep.

**Comment by simov** [comment]
Can you post the code of your callback handler, at least the relevant bits? You are saying that you have this in your callback:

```js
const authData = querystring.parse(ctxt.response.body)
```

But Grant never returns the response data there, it's either in the request querystring or in the session.

**Comment by insidewhy** [comment]
It used to return it there, but not since `4.7.0`. Since I should be pulling it from the session I'll continue to do that.
