### ISSUE TITLE
using grant locally.

### ISSUE THREAD

**Issue by MarcMcIntosh** [simov/grant#16]
ha any one manged to get this to work locally?

I've tried the following with varying levels of failure:
make domain name /etc/hosts and use that, which all most worked (URL issues),
use "http:/localhost:8000/connect/github" sort ofworked with some but not offten.
use "http://127.0.0.1:8000/connect/github" much the same no auth.

Tried the examples... got much the same results.
would using a domain pointed to my local ip and network address work?

**Comment by simov** [comment]
Hi @MarcMcIntosh take a look at this [article](https://scotch.io/tutorials/implement-oauth-into-your-express-koa-or-hapi-applications-using-grant) that I wrote about Grant. There you can find more detailed information about how to use it.

**Comment by MarcMcIntosh** [comment]
That was you?... nice, I've already read through it though... if i recall right some of the errors i got were.

 provider.protocol = options.protocol||config.server.protocol
                                                                              ^
TypeError: Cannot read property 'protocol' of undefined

And face book saying that i was using an unauthorised url.... along with no redirect after the callback, 

Thanks fo writing back so quick :) 

Just to confirm where the config file says "key": "[APP_ID]", that's not a literal value is it? becauses i've been replacing the caps and brackets with my keys :/

**Comment by simov** [comment]
If you take the most basic [example](https://github.com/simov/grant/tree/master/example/express) all you need to do to configure Facebook is to set your app like [this](https://cask.scotch.io/2015/02/fb6.png), the App ID and App Secret is what you paste in the config.json file as key and secret for Facebook. Ofc you have to add `dummy.com 127.0.0.1` to your `hosts` file too, that's all.

**Comment by simov** [comment]
Specifically Facebook allows `http://localhost:3000` to be set as Site URL (which refers to the redirect URL) So if you set `http://localhost:3000` in your Facebook app you will be able to initiate the flow from localhost from your web site like this `http://localhost:3000/connect/facebook`

Some providers doesn't allow `localhost` for redirect URL, that's why all of the examples are using `dummy.com`

**Comment by MarcMcIntosh** [comment]
ohh, that explains alot... 
thanks :)

**Comment by simov** [comment]
No problem, I'm closing this issue.
