### ISSUE TITLE
session-cookie doesn't work with redirect

### ISSUE THREAD

**Issue by kevinsimper** [simov/grant#165]
It is not possible to update a cookie in a redirect, therefore if npm `cookie-session` module is used and redirect, the data is never set here:
https://github.com/simov/grant/blob/master/lib/handler/express-4.js#L45

Here is the debugger showing the data exist and it does a redirect, but the http header `set-cookie` is never done:

![image](https://user-images.githubusercontent.com/1126497/82758481-16939b80-9de7-11ea-9068-409d5707798b.png)

Here is a issue that also confirms it: https://github.com/expressjs/cookie-session/issues/70#issuecomment-265501578

I don't think this example with cookie-session works: https://github.com/simov/grant/blob/master/examples/handler-express/cookie-session.js#L8

**Comment by simov** [comment]
Hi @kevinsimper, the cookie-session example definitely works, you can try it yourself. Can you share your configuration and/or Express setup, might something misconfigured on your end.

**Comment by kevinsimper** [comment]
I researched some more and it looks like this is the problem, the length of the cookie to be set is too long: https://github.com/pillarjs/cookies/issues/125

**Comment by simov** [comment]
That makes sense, in this case try to trim down the [`response`](https://github.com/simov/grant#session-1) data that Grant is delivering. If that doesn't work then you can try using the [`state`](https://github.com/simov/grant#state) transport instead. Here is the [example](https://github.com/simov/grant/tree/master/examples/callback-state) for it. The gist of it is that you can omit the final redirect and receive the response data in the next handler after the Grant middleware.

**Comment by kevinsimper** [comment]
That makes sense! I will do that!
