### ISSUE TITLE
Telegram support

### ISSUE THREAD

**Issue by eringiso** [simov/grant#171]
Hi came to know about this repo while using strapi 
can you please add support for telegram login

**Comment by simov** [comment]
I can't find any relevant information regarding OAuth and Telegram in their [API docs](https://core.telegram.org/api).

**Comment by eringiso** [comment]
here are the links that i found for the login
https://telegram.org/blog/login
https://core.telegram.org/widgets/login

**Comment by simov** [comment]
I saw those too, unfortunately that doesn't look like a regular OAuth implementation to me. It looks like after you navigate to the authorization page you are being redirected back with the user response data to your server, that you can verify then.

Grant is about either OAuth 1.0a, or the `authorization_code` grant of OAuth 2.0.

**Comment by eringiso** [comment]
Thanks for looking into it i'm closing this issue now
