### ISSUE TITLE
Intuit OAuth2

### ISSUE THREAD

**Issue by coolalpaca** [simov/grant#177]
It appears that `intuit` no longer supports oauth1 (as of December 2019): https://developer.intuit.com/app/developer/qbo/docs/develop/authentication-and-authorization/oauth-1.0a

And, the domain for the url that grant is using doesn't even exist anymore - oauth.intuit.com is now oauth.platform.intuit.com.

Seems to be a straightforward fix - I'm just working on a PR. I'll submit it as soon as I have a chance to test it with the actual provider!

**Comment by simov** [comment]
What happened, I saw your commits over [here](https://github.com/PaintScout/grant/commits/master)?

**Comment by coolalpaca** [comment]
Yes indeed! I just created a PR for that!

**Comment by simov** [comment]
Resolved in #180
