### ISSUE TITLE
Session details lost after redirect from keycloak 

### ISSUE THREAD

**Issue by khalilnafis** [simov/grant#185]
Receiving the following error: error=Grant: missing session or misconfigured provider

The provider (keycloak) is configured successfully via Strapi, however in the callback /connect/keycloak there are missing session details:

`{
  method: 'GET',
  params: { provider: 'keycloak' },
  query: {},
  body: {},
  state: {},
  session: {
    provider: 'keycloak',
    state: undefined,
    nonce: undefined,
    code_verifier: undefined
  }
}`

Attempting to trace this to understand where/how the session data is being lost.

**Comment by simov** [comment]
Can you post your configuration here? Also probably a short example on how to reproduce this in Strapi would be helpful.
