### ISSUE TITLE
how to logout?

### ISSUE THREAD

**Issue by edwardsmarkf** [simov/grant#187]
hello - 

i seem to recall we could log out using grant by doing something like this:

https://mydomain.com/connect/google/logout
--or--
https://mydomain.com/google/logout

is there a recommended way to log out?  i apologize if this has already been covered, but i am unable to find it.

**Comment by edwardsmarkf** [comment]
this looks VERY promising:    https://stackoverflow.com/questions/51946456/how-to-delete-connect-sid-from-cookie

```
  .use('/connect/logout', (req, res, next) => {
        res.clearCookie('connect.sid', {path: '/'}).status(200).send('Ok.');
  })
```

**Comment by simov** [comment]
Grant intentionally does not cleanup the session store data and cookie, so that you can have control over it. Depending on the session store that you use you can cleanup the data stored in your database and set the cookie to empty string with maxAge set to 0. That will end the session when the user closes the browser.

There might be other ways to do it, but that's definitely not built into Grant. In fact the session was never meant to be persistent, as far as Grant is concerned once you receive back the access token the session is no longer needed, so it's up to you what to do next.

**Comment by edwardsmarkf** [comment]
thank you once again, Simov.  i am still unable to come up with any sort of actual way to completely log out, but i have turned the question over to the feathers developers and will see what they suggest:

-----------
**Please share the issue you're having and any relevant information.:**
i am never quite able to get logout to behave the way i believe it should. if i manually delete all the cookies, i am logged out successfully. or, if i am running in chrome incognito mode, log out, close the chroem browser incognito window, and reopen once again in incognito mode, then i am able to log out successfully as well.

otherwise, when i log back in again, somehow the browser (or auth0?) seems to "remember" me and does not prompt me for my password again.

i would like to see a logout where i am indeed prompted to re-enter my password.

my problem: a user might log in successfully as per Auth0, but if they have an invalid email on our SPA. then they have no way to reenter the valid email address unless they flush out the cookies.
-----


you might want to have a look at this:  https://community.auth0.com/t/usage-of-node-and-passport/48086   -- please let me know what you think.

**Comment by simov** [comment]
Not sure about your actual setup, so I can't really tell what's going on.

I prefer not having provider specific examples here, as this module strives to be generic. I will be interested in seeing what you come up with though if you feel like sharing it in any other form.

Just to clarify, Grant just happens to use a session while executing the OAuth flow. The reason being is that cookies and session are the most commonly supported way to persist state. The actual session management and persistence, however, is only needed by your layer and/or the FeathersJS one.

**Comment by edwardsmarkf** [comment]
hi simov - and once again, thank you for your comments.

if you would like to have a look:   https://comptonpeslonline.com/proxyPort20004/  (i will leave the server running)

my problem (besides being "technically challenged" and overly handsome) is that when a user accidentally (yet successfully) logs in using an incorrect email address, they need to either reboot or at least close that browser session(tab) in order to be able to try using a different email address.  or, of course, learn how to actually delete cookies.

this is easily demonstrated using an incognito browser window.

i will be getting paid consulting services with the creators of FeathersJS this week for their opinion.

**Comment by edwardsmarkf** [comment]
hi Simov - i cannot remember if you wanted to know this or not, but i hired a couple of guys from Feathers to solve the issue.  it seems with Auth0 we have to call their own specific "logout" page.  its weird, but i actually sort of remember that from doing something similar on PHP.   in case you are interested:

`(async () => { try { await feathersApp.logout(); window.location='https://dev-2XXXXX8.auth0.com/v2/logout?returnTo=https://mydomain.com/proxyPort20004/' } catch (e) { console.log(e); } } ) () ;`
