### ISSUE TITLE
Subsequent Request Cause State Mismatch when user is not logged in.

### ISSUE THREAD

**Issue by talivodworks** [simov/grant#188]
Hello There!
Please take a look at [this stackoverflow](https://stackoverflow.com/questions/63448921/grant-provider-oauth-state-mismatch-when-accessing-the-two-application-modules-s) question and let me know what I am doing wrong. Is this the right way to achieve what I am trying to do. Any help Or Suggestion would be very greatful.

Thank You..

**Comment by simov** [comment]
See my answer on [StackOverflow](https://stackoverflow.com/a/63534284/1260020)
