### ISSUE TITLE
No config for cognito

### ISSUE THREAD

**Issue by JiboStore** [simov/grant#189]
Hi, first of all thank you very much for publishing this awesome library

I am using this through Strapi as I need to integrate with AWS Cognito User Pool, I've been modifying their code to try to make it work, however, the configuration for cognito isn't available either in Strapi, Grant, or Grant's Provider Config.

I've been searching and shooting blindly for the config and managed to get the login working, however once I got the accessToken and try to fire cognito's /oauth2/userInfo endpoint to retrieve the user's info, I got this error: “Access token does not contain openid scope”

Interesting thing is, your OAuth Playground (https://grant.outofindex.com/) works well with cognito, and if I use the access token returned by the Playground, it works without error and I can retrieve the userInfo..

Would you mind publish the config for cognito that is used in the Playground?

Thanks again!

**Comment by simov** [comment]
Hi @JiboStore, make sure you pass the correct scopes when trying to login.

Here is what I have as available scopes for `cognito` in the showcase app:

```json
"cognito": [
  "openid",
  "email",
  "phone",
  "profile",
  "aws.cognito.signin.user.admin"
],
```

Usually it is the `openid` scope that is needed, but you can try requesting any or all of them to see which one grants access to the user endpoint.

**Comment by simov** [comment]
Let me know if you have any other issues.
