### ISSUE TITLE
AWS API+Lambda oauth issue

### ISSUE THREAD

**Issue by biswajitdas** [simov/grant#190]
Hi,

We were not able to configure Google OAUTH.
Nodejs Version : 12
Config Used
```
{
  config: {
    "defaults": {
      "origin": "https://XXXXXX.XXXXX.XXXXXX.amazonaws.com",
      "prefix": "/stage/connect",
      "transport": "state",
      "state": true
    },
    "google": {
      "authorize_url": "https://accounts.google.com/o/oauth2/auth",
      "access_url": "https://accounts.google.com/o/oauth2/token",
      "oauth": 2,
      "scope_delimiter": " ",
      "key": "XXXXXXXXXXXXXXXXXXXXXXXX.apps.googleusercontent.com",
      "secret": "XXXXXXXXXXXXXXXXXXXXXXX",
      "scope": [
        "email",
        "profile",
        "openid"
      ],
      "nonce": true,
      "custom_params": {
        "access_type": "offline"
      },
      "callback": "/response"
    }
  },
  session: {
    secret: 'grant'
  }
}
```

Issues found at first
1. No value found on `event.requestContext.path` so made `event.requestContext.path = event.rawPath;` at lambda.
2. No value found on `event.httpMethod` so made `event.httpMethod = event.requestContext.http.method;` at lambda.

After then it went ahead. But then got stuck in session and getting this error `Grant: missing session or misconfigured provider`.

Can you please let me know where did I go wrong?

Thanks.

**Comment by simov** [comment]
It's because you are using the Event v2 Format.

I'll have a look at it, but in the meantime can you pick the old v1 instead when configuring your gateway?

**Comment by biswajitdas** [comment]
I am not sure how to do that? Does AWS Support that?

**Comment by biswajitdas** [comment]
Ok, I will try that.
Thanks.

**Comment by biswajitdas** [comment]
Thanks, V1 event worked for me.

**Comment by simov** [comment]
Event v2 support added in Grant v5.4.1 see https://github.com/simov/grant/issues/192#issuecomment-691924556
