### ISSUE TITLE
Is there anyway to find that we have a success or error or final callback?

### ISSUE THREAD

**Issue by biswajitdas** [simov/grant#191]
Hi,
Is there anyway to find the final callback?

Thanks.

**Comment by simov** [comment]
Yes, have a look at the [response data](https://github.com/simov/grant#callback-data) structure. If the OAuth flow failed the `error` key will be present, otherwise it was a success.

**Comment by biswajitdas** [comment]
Thanks, Actually I wanted know, whether it is in last redirect or not.

**Comment by simov** [comment]
In any case you will receive either `error` or the expected response data. If the error occurred during the authorization step, for example the authorization server returned an error or the user denied access, then you will see that error. If the error occurs on later stages of the OAuth flow, then you will see that other error instead.

Grant returns specific error messages only for known errors. Any other error is returned as it is, meaning that it depends on the implementation of the authorization server, and that error can be anything, or no error message at all.

**Comment by biswajitdas** [comment]
Actually in my config I have "callback": "https://www.domain.name/login" and I am generating an unique id to pass the details to make them login. For that I am generating unique url for callback "https://www.domain.name/login/1234-4567-789".
How can I do that?

**Comment by simov** [comment]
Not sure I understand the question.

**Comment by simov** [comment]
Let me know if you have any other issues.
