### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by ilanbiala** [simov/grant#2]
Can we get a changelog put together for this package?

**Comment by simov** [comment]
Hi @ilanbiala , thanks for reminding me about this one.

I just added notes about the last two releases here https://github.com/simov/grant/releases

There is only one breaking change in the latest **major** release, that is about the OAuth response data format returned by Grant.

Other than that you should really switch to the latest release, as the previous ones had various bugs in them.

Also I'll think about adding a real CHANGELOG :+1:

**Comment by simov** [comment]
Still no _real_ changelog, the next major release is here https://github.com/simov/grant/releases/tag/3.0.0 check it out for braking changes!

**Comment by simov** [comment]
@ilanbiala [changelog](https://github.com/simov/grant/blob/master/CHANGELOG.md) :tada:
