### ISSUE TITLE
express: TypeScript error with latest type definitions

### ISSUE THREAD

**Issue by endel** [simov/grant#208]
Hi @simov, I'm sorry to bother you, but it seems the TS definitions are broken using latest versions of grant + express

```typescript
src/routes/auth.ts:18:32 - error TS2339: Property 'grant' does not exist on type 'Session & Partial<SessionData>'.

18   const profile = req.session?.grant?.response?.profile;
```

**Dependencies:**

- grant@5.4.9
- @types/express-session@1.17.3
- @types/express@4.17.9

**By reverting the dependencies to these versions, the TS error is gone:**
- grant@5.4.5
- @types/express-session@1.17.0
- @types/express@4.17.8

**Comment by simov** [comment]
Hi @endel, can you check if [this](https://github.com/simov/grant-types/blob/master/examples/transport-session/express.ts) works for you?

**Comment by vogler** [comment]
@simov Thanks! The only change to the js example that's required for ts is to extend the `grant` field:
~~~ts
const session = req.session as typeof req.session & { grant: GrantSession };
~~~

**Comment by endel** [comment]
Thanks, I'm going to use your solution @vogler 🎉
