### ISSUE TITLE
Grant does not return raw data as part of response

### ISSUE THREAD

**Issue by devYusuf** [simov/grant#210]
Hello, I started a project and decided to use grant to handle the twitter oauth and all went well except that it does not return the user raw data.
I expected the response to be some thing like this:
```json 
"response": {
   "oauth_details": "blah blah...",
   "raw": {
     "oauth_token": "1342217994294980609-Yqq8S0rAHWJGY3VNDTQKrlhwCXAOST",
     "oauth_token_secret": "Cdc7LKmzxJxUGcozqM1rLyIqUnVho4UmD8234iYeW7CCV",
     "user_id": "1342217994294980609",
     "screen_name": "photon022"
   }
}
```
but i'm getiing this:
```json
"response": "https://api.twitter.com/oauth/authenticate?oauth_token=k-3rJQAAAAABLCK8AAABdqiAWIs"
```

this is my config file:
```js
const grant = {
    "defaults": {
        "origin": "https://twitter-at-stake.herokuapp.com/",
        "transport": "session"
    },
    "twitter": {
        "key": process.env.TWITTER_API_KEY,
        "secret": process.env.TWITTER_API_KEY_SECRET,
        "callback": "https://twitter-at-stake.herokuapp.com/callback/twitter",
        "redirect_uri": "https://twitter-at-stake.herokuapp.com/callback/twitter"
    }
}

export default grant
```

please what could i be doing wrong?

**Comment by simov** [comment]
Your `redirect_uri` have to be `https://twitter-at-stake.herokuapp.com/connect/twitter/callback`. Set that in your OAuth app on Twitter as well.

**Comment by devYusuf** [comment]
I already set it, but how then do I get the user details from the response?

**Comment by simov** [comment]
Your configuration is incorrect, it have to be `/connect/twitter/callback`.

**Comment by devYusuf** [comment]
Thank you, it worked :100:
