### ISSUE TITLE
ERROR	Cannot find module './lib/handler/undefined' for fastify

### ISSUE THREAD

**Issue by annymosse** [simov/grant#211]
same as the title above :)

**Comment by simov** [comment]
Check out how the various types of constructors work - https://github.com/simov/grant#misc-handler-constructors. You have the specify `handler` name when using the `grant()` one.

**Comment by annymosse** [comment]
if i use that example:
```js
var fastify = require('fastify')
var cookie = require('fastify-cookie')
var session = require('fastify-session')
var grant = require('grant').fastify()

fastify()
  .register(cookie)
  .register(session, {secret: 'grant', cookie: {secure: false}})
  .register(grant({/*configuration - see below*/}))
```
i get that error but when i use the following example:
```js
var fastify = require('fastify')
var cookie = require('fastify-cookie')
var session = require('fastify-session')
var grant = require('grant')

fastify()
  .register(cookie)
  .register(session, {secret: 'grant', cookie: {secure: false}})
  .register(grant.fastify({/*configuration - see below*/}))
```
I don't get the error, thanks for your guidance ,i will try the rest methods other time , as currently i'm just discovering this package.

**Comment by simov** [comment]
Both should work, check your code. You are most likely using this:

```js
var grant = require('grant')

  .register(grant({/*configuration - see below*/}))
```

Which won't work.

**Comment by annymosse** [comment]
nope i checked in my whole commits histories to see where i had the problems , and all of them happened as i mentioned , also i used it with TS as following:
```ts
...
import fastifySession from "fastify-session";
import fastifyCookie from "fastify-cookie";

import qs from "fastify-qs";
import grant from "grant";

const configs = {
  defaults: {
    origin: "....",
    transport: "querystring",
  },
  github: {
    key: "....",
    secret: "......",
    callback: "....",
  },
};

grant.fastify();

export function App(opts = {}) {
  const app = fastify(opts);

  app.register(qs);
  app
    .register(fastifyCookie)
    .register(fastifySession, {
      secret: process.env.SECRET_KEY as string,
      cookie: { secure: false },
    })
    .register(grant(configs)); // <========= doesn't work
   ...
}
```

when i traced the error i realized the problem happened in the following line of file
https://github.com/simov/grant/blob/41dc39392e71113c21651670cf85e4240910769f/grant.js#L21 where it doesn't provide the handler 
```ts
...
    .register(grant(configs));// <====== here
...
```

**Comment by simov** [comment]
```js
};

// the error is in this line
grant.fastify();

export function App(opts = {}) {
```

Check out the return value in the type definition. Grant returns the middleware, so you have to either assign it to a variable or pass it directly to fastify:

```js
import grant from "grant"

// both are identical, pick one:
.register(grant.fastify(configs))
// or
const middleware = grant.fastify()
.register(middleware(configs))
```

That's eager vs lazy loading, you can read about it.
