### ISSUE TITLE
What does "callback" & "transport" do ?

### ISSUE THREAD

**Issue by Twiggeh** [simov/grant#213]
The docs say that  
> callback - relative route or absolute URL to receive the response data /hello | https://site.com/hey ...`

I have probably done something wrong, but it doesn't seem to ever redirect to that url. At first I thought  it would set the `redirect_uri` for the oauth service which it doesn't, and after authenticating and getting redirected to `redirect_uri` it also doesn't redirect to the specified `url`.

Similar issue with `transport`, the `redirect_url` in my case receives all data per query strings, despite having transport set to `session`. 

I am sorry if I didn't configure it correctly 

```js
app.use(
	grant.express({
		defaults: {
			origin: 'http://localhost:5050',
			transport: 'session',
			prefix: '/oauth',
			state: true,
		},
		google: {
			key: googleKey,
			secret: googleSecret,
			scope: ['openid'], // ['openid', 'profile', 'email'],
			nonce: true,
			custom_params: { access_type: 'offline' },
			callback: '/hi',
			redirect_uri: 'http://localhost:5050/googleCallback',
			transport: 'session',
		},
	})
);
```

When I set the `redirect_uri` to the schema specified in the docs `[origin][prefix]/[provider]/callback` (http://localhost:5050/oauth/google/redirect) it just loops back infinitely to the "select account" screen.

**Comment by simov** [comment]
The `redirect_uri` is the redirect URL of your OAuth app, the one you specify in the provider's website for your OAuth app. The `callback` is where you receive the (final) response data when using the querystring `transport`.

The `redirect_uri` as mentioned in the docs can only be `http://localhost:5050/oauth/google/callback` in your case, it have to end with `callback` for Grant to pick it up.

**Comment by Twiggeh** [comment]
Thank you for the fast response!
As I thought I was blind (:

Thanks for making this, stay safe and I wish you a happy new year :D
