### ISSUE TITLE
Request logs not working

### ISSUE THREAD

**Issue by ivandotv** [simov/grant#214]
I'm trying the examples in the repository and it seems that debugging doesn't work.
Go to `dynamic-proxy` and run:
```
DEBUG=req,res node express.js
```
There are no logs printed to the console when hitting the `/hello` route

**Comment by simov** [comment]
Hi @ivandotv, the debug logs mentioned in the docs are only concerned with requests being made by the internal HTTP client used in Grant. Your callback `/hello` route is handled by the HTTP framework, so for that you'll have to use a logger library for Express.

**Comment by ivandotv** [comment]
Got it, thanks.
