### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by zefexdeveloper** [simov/grant#221]
I'm kinda newbie with authentication in general so I have a few questions:

- I have a frontend in React and an API using grant, how can I authenticate the user on a social platform and return the token for him?
- Why is session required? Will the server also generates a cookie? I'm asking this cause I plan on creating a mobile app using React Native and it doesn't work that well with cookies and that is why I want to use JWT instead. Or it has nothing to do with thing with the other?
- Is there a JWT example?
- I couldn't understand the differences on the examples folder, the readme doesn't seem to be updated. What is dynamic-http, dynamic-proxy and dynamic-state?

Thank you

**Comment by simov** [comment]
> I have a frontend in React and an API using grant, how can I authenticate the user on a social platform and return the token for him?

Take a look at this [article](https://dev.to/simov/oauth-like-a-boss-2m3b). One of the examples there is about authenticating from a frontend app. There is a link to that app as well, it's not a React one but hopefully it will help you to understand how it works.

> Why is session required? Will the server also generates a cookie? I'm asking this cause I plan on creating a mobile app using React Native and it doesn't work that well with cookies and that is why I want to use JWT instead. Or it has nothing to do with thing with the other?

Session is required only during the OAuth flow, that's how it works, but after that you can generate a JWT and return that to your users. 

> Is there a JWT example?

In an attempt to cleanup the examples I removed the JWT one and never added it back, but you can take a look at it [here](https://github.com/simov/grant/tree/v4.7.0/examples/jwt).

> I couldn't understand the differences on the examples folder, the readme doesn't seem to be updated. What is dynamic-http, dynamic-proxy and dynamic-state?

The example names are following the configuration sections in the readme, and trust me the readme is up to date as well.

- https://github.com/simov/grant/tree/master/examples/dynamic-http
- https://github.com/simov/grant#dynamic-http

---

- https://github.com/simov/grant/tree/master/examples/dynamic-proxy
- https://github.com/simov/grant#dynamic-oauth-proxy

---

- https://github.com/simov/grant/tree/master/examples/dynamic-state
- https://github.com/simov/grant#dynamic-state

---

- https://github.com/simov/grant/tree/master/examples/transport-querystring
- https://github.com/simov/grant/tree/master/examples/transport-session
- https://github.com/simov/grant/tree/master/examples/transport-state
- https://github.com/simov/grant#callback-transport

**Comment by zefexdeveloper** [comment]
@simov That is amazing, thank you very much for dedicating your time to help me out. I'm currently using passportjs but I'm feeling like it's not being updated in a very long time.
I will be reading all the links and trying things out for sure, thank you very much for that and I hope you are okay with me sending more questions later if I have. I think that a lot of people might be helped with this issue here.

**Comment by simov** [comment]
For new users to this topic or this module in particular I would suggest the following:

1. Pick this example first https://github.com/simov/grant/tree/master/examples/transport-session and pick the HTTP framework you are most comfortable with
2. Take a look at the basics https://github.com/simov/grant#configuration-basics
3. Configure 3 different providers you want and get them working with Grant

You don't need to know all of the details to get things going.

**Comment by zefexdeveloper** [comment]
@simov One thing I always wonder is: imagine an application that uses Grant not only for logging the user in storing on the database the user id coming from the provider (Facebook, Google, etc) but also storing the access token so I can do things such as posting on the user timeline based on actions s/he does, what would be the best way to store that access token knowing that it will eventually expire? I know that I can also store the refresh token but not all providers have that (Facebook for instance)? I use a few websites that I connect my Twitter account and it will never bother me again asking for another authentication and it will continue posting on my timeline for me, how they do that?

**Comment by simov** [comment]
Yes, Facebook is an exception in that regard. They assume that your user will always be around a browser agent where you can redirect them to the authorization URL and refresh the access token.

This was the related question on StackOverflow https://stackoverflow.com/questions/31444237/how-to-programmatically-login-to-facebook-oauth2-api/31502187#31502187 and the subsequent 'module' that I did https://www.npmjs.com/package/facebook-refresh-token about it.

This approach relies on the fact that you are logged in into your personal Facebook account, hence the cookie is valid. Then you configure the background service to use your cookie to refresh the token.

Another approach that I used at some point was to run Puppeteer on a server which gives you the full headless browser where you can login and automate whatever your want.

Neither of these approaches is perfect but that's how it is with Facebook.
