### ISSUE TITLE
Grant playground stopped working

### ISSUE THREAD

**Issue by venkateshgopalakrishnan** [simov/grant#223]
Hi,
I just noticed that the playground hosted at **https://grant.outofindex.com/** has stopped working. When I open the page, It shows nothing but the title. I am not sure if it's relevant to this repository. I am raising the issue here since I couldn't find the source code for the playground.

![image](https://user-images.githubusercontent.com/16909852/106232095-2dfa1280-6219-11eb-9fae-5229700c9251.png)

**Comment by simov** [comment]
Thanks for pointing that out. DigitalOcean had a faulty machine that they replaced yesterday, and I forgot to check back if everything was working correctly after that. Usually these type of issues does not affect running servers, but it seems that this time it was more serious and for some reason the underlying Node.js server that Grant runs on was not started.

**Comment by venkateshgopalakrishnan** [comment]
You are welcome. Thanks a lot for this wonderful library which is saving a lot of our time and efforts during implementation. We would be glad if you can provide the source code for the playground too just for reference. Thanks again.

**Comment by simov** [comment]
Yes, I understand, that app is not published yet, though the contents of it is hardly a secret. It's an Express middleware that's about 100 lines of code or less, and the frontend is in the browser anyway.

But you can check out my comment here https://github.com/simov/grant/issues/61. As for hooking this up with your frontend application you can take a look at [this article](https://dev.to/simov/oauth-like-a-boss-2m3b).

Let me know if you have any questions.
