### ISSUE TITLE
Set origin automatically?

### ISSUE THREAD

**Issue by vogler** [simov/grant#227]
Is there a way to not have to manually set origin? I currently have it in env, but would be nice to get rid of it.
I'm using express. Is `req.headers.host` reliable or is there a better alternative?

**Comment by simov** [comment]
Not sure, you have to test it.

**Comment by vogler** [comment]
This works for me and allows to override it:
~~~ts
app.all('/connect/:provider', (req, res, next) => {
  const origin = process.env.auth_origin ?? req.headers.referer?.replace(/\/$/, '') ?? `https://${req.headers.host}`;
  res.locals.grant = {dynamic: {origin}};
  console.log(req.originalUrl, res.locals.grant);
  next();
});
~~~
I don't know if it makes sense to integrate something like this. If not, you can close this.
I assume `referer` is unreliable, and with `host` you have to guess the protocol.

**Comment by simov** [comment]
Looks like a good solution :+1: 

Let me know if you have any other questions.
