### ISSUE TITLE
Identical Grant Configs, one works the other doesn't 

### ISSUE THREAD

**Issue by Twiggeh** [simov/grant#229]
I cloned my old server and updated keys to point to a new google app. But for whatever reason I am getting the session is undefined or grant is misconfigured. I stepped through grant and the session did exist & was actually persisted to the session store. 

I am now 100% uncertain what to do, since grants config is identical to the other one, the server is also identical. The only thing that changed were the keys for google. The old app still works fine, so google didn't change anything on their end. Am I missing some setup with a google provider ? I dont know. [This google guide thing is useless, half of what it asks you to do doesnt exit !](https://support.google.com/googleapi/answer/6158849?hl=en#zippy=%2Cuser-consent)

![image](https://user-images.githubusercontent.com/23149166/110237216-f3cc1100-7f3a-11eb-8f8e-8a8a03acce66.png)

The problem seems to be that provider in request/callback is empty on after I click on the user . I am not sure what the causes its 
non existance. On the other app it exists.

```
app.use(
	grant.express({
		defaults: {
			origin: SERVER_URL,
			transport: 'session',
			prefix: '/oauth',
			state: true,
		},
		google: {
			key: googleKey,
			secret: googleSecret,
			scope: ['openid', 'profile', 'email'],
			nonce: true,
			custom_params: { access_type: 'offline', prompt: 'select_account' },
			callback: '/auth_redirect/google',
			//redirect_uri: 'http://localhost:5050/auth_redirect/google',
		},
	})
);
```

![image](https://user-images.githubusercontent.com/23149166/110237375-04c95200-7f3c-11eb-9d5a-9c89b124d423.png)

**Comment by simov** [comment]
What is the redirect URI of your OAuth app?

**Comment by Twiggeh** [comment]
> What is the redirect URI of your OAuth app?

https://cdn.discordapp.com/attachments/694508622519992350/818057403898921010/unknown.png

**Comment by simov** [comment]
Yes, that's what I meant. Another thing you can try is to make sure you have the exact npm versions of your modules installed in both places. Assuming that the ones on your first deployment might use a bit older versions, and your new install can have some minor or patch versions installed. You have to look for your session middleware and Grant obviously, just to rule it out.

**Comment by Twiggeh** [comment]
> Yes, that's what I meant. Another thing you can try is to make sure you have the exact npm versions of your modules installed in both places. Assuming that the ones on your first deployment might use a bit older versions, and your new install can have some minor or patch versions installed. You have to look for your session middleware and Grant obviously, just to rule it out.

Yes grant is the same in both, same as all of the other middleware (I cloned the projects from the same template)

If you have time and (you want to ofc, thank you for taking the time to help me on a sunday :D) I can give you access through vscodes liveshare

**Comment by simov** [comment]
Thanks, but I'm looking at a few other issues as well. Another thing you can try is to cleanup your browser cookies and cache, even easier you can use another browser or incognito mode. There is a chance that you are still using your old session, the one you used to login with app A, that is now preventing you from logging into app B.

**Comment by Twiggeh** [comment]
> Thanks, but I'm looking at a few other issues as well. Another thing you can try is to cleanup your browser cookies and cache, even easier you can use another browser or incognito mode. There is a chance that you are still using your old session, the one you used to login with app A, that is now preventing you from logging into app B.

Incognito mode has worked, so something is up with the cookies! I should've thought of that sooner, my bad. 

Thank you so much for your time, have a wonderful rest of a weekend ^~^
