### ISSUE TITLE
Type errors in request-compose and grant 5.4.11

### ISSUE THREAD

**Issue by daffl** [simov/grant#235]
I am getting TypeScript compilation errors with the recently released version 5.4.11 from `request-compose`:

<img width="870" alt="Screen Shot 2021-03-20 at 12 57 45 PM" src="https://user-images.githubusercontent.com/338316/111883991-e1f75e80-897b-11eb-9a89-c2b3e48ace7c.png">

**Comment by simov** [comment]
I was about to fix that, not sure how I missed it.

**Comment by simov** [comment]
Published the fix with v5.4.12

I set that type to `any` until I figure out a better way to do it. It's an edge case anyway. Also for some reason my test tsconfig was not catching this error, so I cleaned it up and I was able to reproduce it.

Let me know if you find anything else.

**Comment by daffl** [comment]
Thank you!
