### ISSUE TITLE
Native steam OpenID support?

### ISSUE THREAD

**Issue by Moonded** [simov/grant#238]
I've come to notice that steam is not supported by default. I have seen i could add it by adding custom provider. Would it be possible to add steams openID auth to the default suport list? 

I'm currently simply playing with new options and came across grant due to directus cms.

**Comment by simov** [comment]
Hi, @Moonded, have a look at this answer https://github.com/simov/grant/issues/140

**Comment by Moonded** [comment]
Thanks for pointing me to that. I didn't read that sofar as I am currently not home yet. Looks like I need to use another auth provider.

Thanks anyway
