### ISSUE TITLE
How to install / getting started

### ISSUE THREAD

**Issue by maxwellmckinnon** [simov/grant#245]
I'm at a loss for how to use this. I'd like to use it to handle the OAuth for the Strava API for my small Strava web app site. The playground demo does exactly what I need. (I'm a noobie web dev, first web project).

If it's something complicated, I'd be willing to write up a GettingStarted.md and link to it from the main readme.

**Comment by simov** [comment]
Check out this [article](https://dev.to/simov/oauth-like-a-boss-2m3b), it touches a little bit on what you need to do in the browser as well. 

Such guide can't be part of this repository as it's out of scope, and then also impossible to cover all frontend frameworks and nuances. Start with a blank page and try to get it working with vanilla javascript using the example in that article. It's really a few lines of code. Once you get that working and understand how it works, then you can apply your knowledge on any frontend framework.

Also this [example](https://github.com/simov/grant/tree/master/examples/dynamic-http) have a login form in it. Once you start the server you can navigate to the `/login` route. This is exactly what the playground app is doing as well.

**Comment by maxwellmckinnon** [comment]
That's the very article that led me to this repo ;)

Haha thanks! I ended up getting it working thanks to http://www.passportjs.org/packages/passport-strava/
