### ISSUE TITLE
getting { error: 'read ECONNRESET' } in callback for no reason

### ISSUE THREAD

**Issue by venkateshgopalakrishnan** [simov/grant#248]
Hi, I am not sure if this is a problem with Grant. But I just wanted help on this. 

I can see that I am being redirected from the IdP with a code in the URL like this - _/connect/provider/callback?code=<>_.
But from here when we enter the callback route I get **{ error: 'read ECONNRESET' }** in _req.session.grant.response_. Not sure why this happens in the first place. Can anyone help me on this?

**Comment by simov** [comment]
Can you run your server using:

```bash
npm i --save-dev request-logs
DEBUG=req,res,json node app.js
```

This will print out the full request/response longs for the internal HTTP request that Grant is doing.

**Comment by venkateshgopalakrishnan** [comment]
While the same application gives me the full set of logs including the JWT in my local, I am only getting half of that in my remote server. It just gave me this when I ran it on my remote server...
```
req POST https://dev-83090317.okta.com/oauth2/default/v1/token
    user-agent:     simov/grant/5.4.12
    content-type:   application/x-www-form-urlencoded
    content-length: 254
    Host:           dev-83090317.okta.com
form
    grant_type:    authorization_code
    code:          iuhN359fIY2HEAjZ6ERnDsga_9j8cXtslsWKUH4OUjA
    client_id:     0oakelitgEz7JGudA5d6
    client_secret: B90OB3n-EkPxktOu4hEJdC4Z9-OpJWWWtUpkiZdW
    redirect_uri:  https://gtfixmypc.adm.com:3000/api/connect/provider/callback
(node:1648461) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headerNames is deprecated
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**Comment by venkateshgopalakrishnan** [comment]
While the same application gives me the full set of logs including the JWT in my local, I am only getting half of that in my remote server. It just gave me this when I ran it on my remote server...

req POST https://dev-83090317.okta.com/oauth2/default/v1/token
    user-agent:     simov/grant/5.4.12
    content-type:   application/x-www-form-urlencoded
    content-length: 254
    Host:           dev-83090317.okta.com
form
    grant_type:    authorization_code
    code:          iuhN359fIY2HEAjZ6ERnDsga_9j8cXtslsWKUH4OUjA
    client_id:     ********************
    client_secret: *******************************************
    redirect_uri:  https://something.somethingelse.com:3000/api/connect/provider/callback
(node:1648461) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headerNames is deprecated
(Use `node --trace-deprecation ...` to show where the warning was created)

**Comment by venkateshgopalakrishnan** [comment]
While the same application gives me the full set of logs including the JWT in my local, I am only getting half of that in my remote server. It just gave me this when I ran it on my remote server...
```
req POST https://dev-83090317.okta.com/oauth2/default/v1/token
    user-agent:     simov/grant/5.4.12
    content-type:   application/x-www-form-urlencoded
    content-length: 254
    Host:           dev-83090317.okta.com
form
    grant_type:    authorization_code
    code:          <some random string>
    client_id:     ********************
    client_secret: *******************************************
    redirect_uri:  https://something.somethingelse.com:3000/api/connect/provider/callback
(node:1648461) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headerNames is deprecated
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**Comment by simov** [comment]
So in case you run your server correctly with all of the debug flags `DEBUG=req,res,json`, then that means that for some reason the token exchange request fails, and you never really receive any response. Otherwise you would have seen the response as well.

**Comment by venkateshgopalakrishnan** [comment]
Seems the issue was with a server-side security policy applied, which prevented the token exchange from happening. Thanks for the help! I will close the issue.
