### ISSUE TITLE
GitHub Oauth: redirect_uri_mismatch

### ISSUE THREAD

**Issue by vital101** [simov/grant#25]
I've been having some issues getting GitHub oauth working with Grant.  I already have BitBucket Oauth set up correctly, so I'm using the library correctly.  My setup:

__GitHub__
My callback URL in GitHub is set to http://local-kernl.com/api/v1/oauth/github/

local-kernl.com is an entry in my /etc/hosts file that directs the user to a virtual machine (vagrant) with Nginx installed.  Nginx then acts as a reverse proxy to localhost:3000 where my Node app lives.

__Node__
My Node config looks like:

```javascript
grant = new Grant({
  "server": {
    "protocol": "http",
    "host": "local-kernl.com",
    "transport": "session",
    "state": true
  },
  "bitbucket": {
    "__provider": {
        "oauth2": true
    },
    "key": "bitbucket-key",
    "secret": "bitbucket-secret",
    "callback": "/api/v1/oauth/bitbucket/",
  },
  "github": {
    "key": "github-key",
    "secret": "github-secret",
    "callback": "/api/v1/oauth/github/",
    "scope": [
      "public_repo",
      "repo",
      "repo_deployment",
      "repo:status"
    ]
  },
});
```
For BitBucket, when I hit `/connect/bitbucket/` it makes the requests as expected and authorizes my app.  With GitHub(`/connect/github/`) though, I get the response:
```
error=redirect_uri_mismatch
error_description=The redirect_uri MUST match the registered callback URL for this application.
```
The error is pretty obvious, but it doesn't look like I have the urls mismatched.  I've tried several different iterations of this, including having it go straight to `localhost:3000` with no luck.  I read through your blog post @ https://scotch.io/tutorials/implement-oauth-into-your-express-koa-or-hapi-applications-using-grant, which I seem to be following correctly

Any help or ideas would be greatly appreciated.  Thanks!

**Comment by simov** [comment]
For [redirect_uri](https://github.com/simov/grant#redirect-url) of your *OAuth application* you should always use this format:

```
http://local-kernl.com/connect/github/callback
http://local-kernl.com/connect/bitbucket/callback
```

The path you set in the `callback` key of your Grant config, is the final route where you get the results. Grant redirects you there after hitting the `/connect/:provider/callback` route that is specified in your OAuth application.

**Comment by vital101** [comment]
Thank you, this was the issue.
