### ISSUE TITLE
Grant should use newer fastify session package

### ISSUE THREAD

**Issue by QEDK** [simov/grant#258]
The package that grant recommends for use with fastify is no longer maintained, grant should use [@fastify/session](https://github.com/fastify/session) for future releases.

**Comment by simov** [comment]
Thanks for the feedback, I'll have a look.

**Comment by QEDK** [comment]
@simov I just tested `grant` with the new package (as simple as changing `require('fastify-session')` to `require('@fastify/session')`) and it worked pretty great with Twitter OAuth (all defaults). Just letting you know. ✌️

**Comment by simov** [comment]
Updated docs and all examples :+1:
