### ISSUE TITLE
grant.outofindex.com not working anymore for FusionAuth

### ISSUE THREAD

**Issue by fanshaohua-fan** [simov/grant#263]
I use the website as the usual way but encounter an error about "certificate has expired".
The certificates of both FusionAuth(auth-mobile-app-staging.loyalty-cloud.com) and grant.outofindex.com are pretty normal, 
Have no clue what could be the reason. 

![image](https://user-images.githubusercontent.com/6319967/138901982-7355b798-94b9-4a82-9008-ef7b4e4ca76e.png)

**Comment by fanshaohua-fan** [comment]
@simov , I run the SSL check on my domain, everything looks good.
see the detail report with the links below:
https://www.ssllabs.com/ssltest/analyze.html?d=auth-development.loyalty-cloud.nl
https://www.sslshopper.com/ssl-checker.html#hostname=auth-development.loyalty-cloud.nl

But I will try to setup FusionAuth locally with certificate, currently it's hosted within Azure Kubernetes Service. not sure if it's related.

**Comment by fanshaohua-fan** [comment]
@simov It encounter the same error for my local setup.
I realize it might be related with the Root certificate expiration from Let's Encrypt.
Maybe the ISRG Root X1 certificate is not trusted by the host of grant.outofindex.com, or a old version openssl is being used.
Can you have a look?

![image](https://user-images.githubusercontent.com/6319967/139529269-646b15e7-95d6-4249-8cce-4517f257bafa.png)

![image](https://user-images.githubusercontent.com/6319967/139529172-635c2da1-4745-403e-985f-d5960de10a21.png)


Check the doc in detail:
https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/

**Comment by simov** [comment]
I verified that I have the `ISRG_Root_X1.crt` certificate on my server, and the OpenSSL version is `1.1.0f`. This is the report about the certificate https://www.ssllabs.com/ssltest/analyze.html?d=grant.outofindex.com

**Comment by fanshaohua-fan** [comment]
@simov , I replaced the certificate of FusionAuth server to another one, which's not issued by Let's Encrypt, then it works.

Can you try to reproduce it with a Let's Encrypt certificate?
Think the reason is that the ISRG_Root_X1 certificate is not trusted by your application, even you have it on the server.

**Comment by simov** [comment]
It seems that node have those root certificates [embedded](https://github.com/nodejs/node/blob/v12.x/src/node_root_certs.h#L2603-L2631).

My server was using node `v8.9.1` released on `2017-12-01`, and the `ISRG` root certificate was added on `2017-04-18` [here](https://github.com/nodejs/node/commit/6331b63ce0e99bc1e5de4e21ea0c9da9df8ab759).

So it should've been there, but worth a try. Now my server is running node `v12.22.7`, can you give it a try?

**Comment by fanshaohua-fan** [comment]
@simov it's working now :+1: 
Thanks a lot for the support and quick fix!
