### ISSUE TITLE
Export the grant config and Options

### ISSUE THREAD

**Issue by Joabesv** [simov/grant#288]
Hi there! thank you for the package!

was wondering if it's possible to export the grant config options interface in the fastify handler!

I'm willing to submit a pr.

**Comment by simov** [comment]
You mean the contents of the `config` folder? Not sure I'm following. As for the config of your Grant instance you can access them on the [`config` property](https://github.com/simov/grant#dynamic-instance).

**Comment by Joabesv** [comment]
Hi there, thanks for the answer

when i say config i'm refering to the typescript types! 

sort of something like this


```ts
import fastifyGrant,  {type GrantConfig } from 'grant-fastify'

const grantOptions = { ... } satisfies GrantConfig
```

so i can use it to assert my config is right!!

**Comment by simov** [comment]
I see, that was my next assumption, but I was not 100% sure. Anyway, now when looking at it, it seems that the underlying interfaces were not exported in the meta modules. Though note that the meta `grant-*` modules are really only package names on NPM. There is 0 code there other than the export for the main module. The main module `grant` contains the entire code base, and it is always better to use that directly.

Have a look at this [example](https://github.com/simov/grant-types/blob/master/examples/transport-state/fastify.ts). Also check out the other folders for the rest of the transport types, there is a `fastify` example for each one of them.

**Comment by Joabesv** [comment]
Using the main module solved it for me, thanks mate!

Appreciate the tips, and again thank you, for your package!
