### ISSUE TITLE
Switch to OAuth 2 for OpenStreetMap provider

### ISSUE THREAD

**Issue by danieldegroot2** [simov/grant#293]
Switch to OAuth 2 from HTTP Basic Auth and OAuth 1.0a. They are being deprecated.
See https://github.com/openstreetmap/operations/issues/867

**Comment by simov** [comment]
Added here https://github.com/simov/grant/commit/c220e9ef812978608a4c05551b3f241e3e9da249, though note that this can be configured and used even with the current release of Grant.
