### ISSUE TITLE
Github oauth: redirect_ui mismatch

### ISSUE THREAD

**Issue by marcelklehr** [simov/grant#31]
Hey,

I'm using grant for github auth in my app and the redirect uri seems to equal `myapp.com/connect/github/callback&state=` instead of `myapp.com/connect/github/callback`.

Here's my config:

```js
{
    server: {
      protocol: 'http'
    , host: 'http://myapp.org'
    }
  , github: {
      key: 'key'
    , secret: 'secret'
    , scope: []
    , callback: '/login_github_callback'
    }
  }
```

**Comment by simov** [comment]
It should be `host:'myapp.org'`.

Here is what I have set up for `Authorization callback URL` of my OAuth app here on GitHub (for the [OAuth Playground](https://grant-oauth.herokuapp.com)):

```
https://grant-oauth.herokuapp.com/connect/github/callback
```

Then in my config I have:

```js
server:{protocol:'https', host:'grant-oauth.herokuapp.com'},
github:{key, secret, scope ...}
```

**Comment by marcelklehr** [comment]
ah, works now. Thank you!

**Comment by marcelklehr** [comment]
Awesome project by the way!

**Comment by simov** [comment]
Thanks :+1:
