### ISSUE TITLE
Multiple handlers with different options

### ISSUE THREAD

**Issue by nestauth** [simov/grant#312]
How safe is it to add multiple handlers, but with different configurations? Something like this:
```js
var app = express()

app.use(session({secret: 'grant'}))
app.use(grant({ defaults: { prefix: 'connect' } }))
app.use(grant({ defaults: { prefix: 'link' } }))
```
I need different routes for different actions:
- for authentication - `/connect/:provider`.
- for linking a social account within a profile - `/link/:provider`.

Is this ok or is there a better option?

**Comment by simov** [comment]
It should be perfectly fine, just note that the Grant instance will be shared in that case, but you can also have separate instances if you want:

```js
var grant1 = Grant(config1)
var grant2 = Grant(config2)
app.use(grant1({ defaults: { prefix: 'connect' } }))
app.use(grant2({ defaults: { prefix: 'link' } }))
```

Or maybe compose your configuration in a different way:

```js
{
  github: {
    // authentication config
    social: {
      // some other config
    }
  }
}
```

And then:
- /connect/github - default
- /connect/github/social - something else

Let me know if that helps.
