### ISSUE TITLE
Problems with Yahoo

### ISSUE THREAD

**Issue by JoeMcMahon87** [simov/grant#33]
I'm using Node and Express 3 and tried the following:

```js
var Grant = require('grant-express')
  , grant = new Grant({
"server": { 
  "protocol" : "http",
  "host" : "[my host]:[my port]"
},
"yahoo": {
  "key": "[OAUTH CONSUMER KEY]",
  "secret" : "[OAUTH SECRET]",
  "callback" : "[host and path for callback]"
}
});

var app = express()
app.use(express.logger())
app.use(express.cookieParser())
app.use(express.cookieSession({secret:'very secret'}))
// mount grant
app.use(grant)
```

When I hit the [host]/connect/yahoo URL, I get the following:
```js
{
  "error": {
    "oauth_problem": "consumer_key_unknown"
  }
}
```

When I try the same consumer key and secret on the OAuth Playground app on your Heroku instance, with the Yahoo provider, it works fine.

**Comment by simov** [comment]
That's very weird. Can you try with the Express [example](https://github.com/simov/grant/tree/master/example/express)? Also the `callback` in your configuration should be something like `/handle_yahoo_callback` check out the example code.

**Comment by JoeMcMahon87** [comment]
So the express example works for Twitter (didn't try Facebook).  I added a config entry for Yahoo with a fresh set of keys/secrets and a handler in app.js and I get the same error.  I am using the callback as ```/handle_yahoo_callback```

**Comment by simov** [comment]
Double check if you copy/pasted your consumer_key correctly from Yahoo. That's really weird I can't figure out what the problem might be in case it works with the showcase app. Search in Google for something like `yahoo oauth consumer_key_unknown` it might be something on their end.

**Comment by simov** [comment]
@JoeMcMahon87 I'm closing this issue for now. Let me know if you have any other issues.
