### ISSUE TITLE
Problem with Trello

### ISSUE THREAD

**Issue by theninthnode** [simov/grant#36]
I'm trying to connect to Trello but it doesn't seem to be working. 

Here's my config:

```
"trello": {
	"key": "***",
	"secret": "***",
	"scope": ["read"],
	"callback": "/authorise/trello",
	"custom_params": {"name":"test", "expiration":"never"}
},
```

Neither the Allow or Deny buttons are working. Looking at the console when clicking Allow it seems to do a POST call to https://trello.com/1/token/approve which is cancelled.

The post data contains: approve, requestKey, signature params.

Any idea what I've done wrong here?

**Comment by simov** [comment]
Works on my end, can you try with this [example](https://github.com/simov/grant/tree/master/example/basic)?

Just copy/paste your config in place of the facebook one. Also check out if the `server` configuration is correct. In case you don't want to edit your hosts file you can probably use `localhost:3000` as a `host` value for Trello.

**Comment by simov** [comment]
Let me know if you have any other issues. Closing.
