### ISSUE TITLE
customized redirect URL ?

### ISSUE THREAD

**Issue by kerphi** [simov/grant#37]
README says that:
>For redirect URL of your OAuth application you should **always** use this format:
>
>[protocol]://[host]/connect/[provider]/callback

But in my application I'd like to use a customized redirect URL, for example:
[protocol]://[host]/myspecificapppath/connect/[provider]/callback

Is it possible ?

**Comment by simov** [comment]
The OAuth redirect URL is used internally by Grant. What you probably you want to is to set up your `callback` URL. I'm giving you an example with Twitter:

1. Setup your OAuth application redirect url to `http://mywebsite.com/connect/twitter/callback`
2. Setup your your server's `callback` which is where you want to receive the **final** response data:

```js
twitter: {
  key: '',
  secret: '',
  callback: '/handle_twitter_callback'
}
```

Notice that the redirect URL of your OAuth app and the path to handle the callback in your app are different. Take a look at the examples, here is the most [basic one](https://github.com/simov/grant/tree/master/example/basic).

Only in very rare cases you really need a custom redirect URL for your OAuth application. Let me know if that's the case.

**Comment by kerphi** [comment]
Thank you.
