### ISSUE TITLE
Grant/Purest use with shopify

### ISSUE THREAD

**Issue by thurstjo63** [simov/grant#38]
Hi, You might have noticed my tweet. I'm trying to use Grant and Purest for an app that I'm writing. The testing was going well. I was able to authenticate in test but once I deployed to Heroku, I ran into "Oauth error invalid_request: The redirect_uri is missing or not whitelisted" error. I mapped it in exactly the same way you did in the Grant demo app but am still getting this error.

As well, I'm not totally clear on how to use Purest. I have a clear idea of the REST api call for shopify but don't see what parameters I need to supply to and in what structure to use it for Shopify. Any and all help will be greatly appreciated.

Kind Regards,

John (legendsofthesport.co)

**Comment by simov** [comment]
The configuration that works locally won't work on Heroku. I'm giving you example with 
https://grant-oauth.herokuapp.com

```js
{
  server: {
    protocol:'https',
    host:'grant-oauth.herokuapp.com'
  },
  shopify: {
    key:'[APP_ID]',
    secret:'[APP_SECRET]',
    callback:'/handle_callback'
  }
}
```

Then I have my Shopify OAuth app redirect URL set to `https://grant-oauth.herokuapp.com/connect/shopify/callback`

**Comment by thurstjo63** [comment]
Simeon, I cannot thank you enough! 

All the best,

John

**Comment by simov** [comment]
No problem, I'm glad it worked!
