### ISSUE TITLE
Express empty req.session.grant 

### ISSUE THREAD

**Issue by noyg** [simov/grant#40]
config:
```javascript
{
	"server": {
		"protocol": "http",
		"host": "localhost:3000"
	},
	"intuit": {
		"request_url": "https://oauth.intuit.com/oauth/v1/get_request_token",
		"authorize_url": "https://appcenter.intuit.com/Connect/Begin",
		"access_url": "https://oauth.intuit.com/oauth/v1/get_access_token",
		"oauth": 1,
		"key": "mykey",
		"secret": "mysecret",
		"callback": "/api/connect/intuit",
		"custom_params": {
			"datasources": {
				"quickbooks": true,
				"payments" : false
			}
		}
	}
}
```

app.js
```javascript
var Session = require('express-session')
    , session = Session({secret: 'very secret', resave: true, saveUninitialized: true})
    , Grant = require('grant-express')
    , grant = new Grant(config.connect);

app.use(session);
app.use(grant);

app.get('/api/connect/intuit', function (req, res) {
	console.log('----------------------------------------------------');
	console.log(req);
	console.log('----------------------------------------------------');
});
```

I'm getting `{"error":"Grant: missing session or misconfigured provider"}`. 
When logging `req.session` in `grant/lib/consumer/express.js:98` I get:
```javascript
{ cookie: 
   { path: '/',
     _expires: null,
     originalMaxAge: null,
     httpOnly: true } }
```

So it seems like the grant details aren't being updated to the session.

I was using this example as reference: https://github.com/simov/grant/tree/master/example/express

What am I missing?

**Comment by simov** [comment]
Seems to be working on my end. I'm going to add `intuit` in the next release.

Your configuration looks correct, although I'm not sure how are these `custom_parameters` actually sent, the documentation isn't clear about that, there is just one example using their own library.

Can you try with [this example](https://github.com/simov/grant/blob/master/example/basic/app.js)? It's essentially the same example as the one you are using, but the configuration is set in the source file. Can you configure it and paste the exact code that you are using (of course without your credentials).

**Comment by noyg** [comment]
@simov you're right, it was something about loading the configuration.

Want me to prepare a pull request for intuit?

**Comment by simov** [comment]
> Want me to prepare a pull request for intuit?

Sure, feel free to submit a PR. I think the 3 URLs and the `oauth` flag would be enough. I can't find any proofs about custom authorization parameters and how they are used in their documentation.
