### ISSUE TITLE
Session managment with Hapijs

### ISSUE THREAD

**Issue by jgauna** [simov/grant#41]
I'm using Grant with Facebook and Twitter and it works great but the problem is when I try to manage the session. The plugin generates a session called ```grant``` when it redirects to the facebook pr twitter login, and not when you logged in successfully. Do I need to use a custom session using yar ? Btw, awesome work ! Thanks.

**Comment by simov** [comment]
> The plugin generates a session called grant when it redirects to the facebook pr twitter login, and not when you logged in successfully.

Can you clarify that? I'm not sure I understand your issue correctly.

**Comment by jgauna** [comment]
As I understand you're using Yar to create a session. This session is created when the route redirects to Facebook or Twitter login page. If my assumption is correct, it's an error because the session should be created when you are logged in and not before. If it's not, how do I get the session in the route handler?

**Comment by simov** [comment]
The `grant` key in your user's session is created once you initiate a flow through the `/connect/[provider]` route.

You can get the contents of this key using:

```js
req.session.get('grant')
```

There you have a bunch of other keys used internally by grant:

```js
{
  // the provider currently being authorized with
  provider: 'facebook',
  // in case you passed dynamic configuration
  dynamic: {},
  // this holds the data returned by the third party after the authorization step
  step1: {},
  // in case you pass `session: true` in your server config,
  // you'll receive the results from the OAuth flow here
  response: {}
}
```

The `dynamic` and the `step1` keys are used internally by Grant. You should handle the contents of the `response` key somehow, and `provider` is just letting you know which provider is this.

Next time you authenticate with some other provider (or the same) all of the keys in the `grant` session object will be overridden.

In case you want to clean up the `grant` object from your session after the OAuth flow is complete, you can:

```js
req.session.set('grant', undefined)
```

In your final callback.

Let me know if that helps.
