### ISSUE TITLE
"response.raw" not containing extra parameters

### ISSUE THREAD

**Issue by noyg** [simov/grant#42]
Using this configuration:
```js
var connectConfig = {
            "server": {
                "protocol": "http",
                "host": "localhost:3000",
                "transport": "session",
            },
            "intuit": {
                "request_url": "https://oauth.intuit.com/oauth/v1/get_request_token",
                "authorize_url": "https://appcenter.intuit.com/Connect/Begin",
                "access_url": "https://oauth.intuit.com/oauth/v1/get_access_token",
                "oauth": 1,
                "custom_parameters": ["realmId", "dataSource"],
                "key": "MY_KEY",
                "secret": "MY_SECRET",
                "callback": "/oauth/connect/intuit"
            }
        }
        ;
app.use(new Grant(connectConfig));
```

When I print `console.log(req.session.grant.response.raw);` I get:

```js
{ oauth_token_secret: 'THE_TOKEN_SECRET',
  oauth_token: 'THE_TOKEN' }
```

Even though I do see a request to the default callback, with those params:
`http://localhost:3000/connect/intuit/callback?oauth_token=THE_TOKEN&oauth_verifier=VERIFIER&realmId=A_CORRECT_REALM_ID&dataSource=QBO`

I'm guessing I'm just doing something wrong here... Any help would be greatly appreciated :)

**Comment by simov** [comment]
The querystring parameters you are seeing are from step2 of the OAuth flow, the final response is after step3. In other words Grant returns to you what the service responds with in the final step3 of the OAuth flow.

Can you point me to the Intuit docs on where are these parameters passed, and how are they supposed to be used?

**Comment by noyg** [comment]
I am just figuring this out. How can I work around this?

Regarding the docs, I think that's what you were referring to:

https://developer.intuit.com/docs/0100_accounting/0060_authentication_and_authorization/connect_from_within_your_app#/2._Get_the_OAuth_access_token-7833

**Comment by simov** [comment]
Got it, that's totally out of the OAuth specification, but I think I can patch my code easily. I'll let you know when it's done. Do you need the `dataSource` parameter as well? I don't see anything about it in their docs and its value seems to be `QBO` for me as well.

**Comment by noyg** [comment]
I do'tt think that the `dataSource ` is necessary for now (at least not for me :) ). I'd be happy if you could point me in the right direction so I can patch it myself for the time being since this is becoming a little urgent on my end.

**Comment by noyg** [comment]
I was thinking about adding something of the sort of:
```javascript
if (provider.intuit) {
          body += '&realmId=' + step2.realmId
      }
```

around here: https://github.com/simov/grant/blob/32f024ab21a245b4a49d3670366313d448a5cdd6/lib/flow/oauth1.js#L92

Otherwise, I think the entire step2 data should be sent to `utils.toQuerystring` and that seems like an overkill.. What do you think?

**Comment by simov** [comment]
Yep that's the spot, I'm about to add it right now, but I'm going to write a test for it, so you might be faster than me.

Sending the entire data is not necessary, it's easier that way, but I want to be explicit in that part of the app.

**Comment by noyg** [comment]
Can I submit a pull request for the provider + fix, just without the test?

**Comment by simov** [comment]
Well, I just pushed some stuff already, so probably won't be needed, though you helped me a lot already. I just can't find anything about the custom parameters and how are they used, so if you can point me to the right place in their docs that would be great. Their docs are definitely not very helpful for library authors.

**Comment by noyg** [comment]
if it's already pushed, I'd love to use your branch instead of my forked one (for future updates), so I'd be more than happy to know once it's pushed.
In regards to documentation, I just used the examples they're providing in https://developer.intuit.com/docs/0100_accounting/0060_authentication_and_authorization/connect_from_within_your_app#/Sample_Implementations and went through to code to make some sense out of it...

**Comment by simov** [comment]
Done!

```bash
npm install https://github.com/simov/grant.git
```

I'm usually releasing the new version by the end of the month.

**Comment by simov** [comment]
Btw, you can now use this configuration:

```js
var connectConfig = {
    "server": {
        "protocol": "http",
        "host": "localhost:3000",
        "transport": "session",
    },
    "intuit": {
        "key": "MY_KEY",
        "secret": "MY_SECRET",
        "callback": "/oauth/connect/intuit"
    }
}
```

I'll let you know when the new version is out.

As for the custom parameters they are probably these:

```html
<script src="https://js.appcenter.intuit.com/Content/IA/intuit.ipp.anywhere-1.3.2.js" type="text/javascript"></script>
<script type="text/javascript">
    intuit.ipp.anywhere.setup({
            grantUrl: 'http://www.mycompany.com/HelloWorld/RequestTokenServlet',
            datasources: {
                 quickbooks : true,
                 payments : true
           },
            paymentOptions:{
                  intuitReferred : true
           }
    });
</script>
```

But I'm not sure, and I don't think I'm going to dig through they library to find out.

**Comment by noyg** [comment]
WOW. Thank you so very much!

**Comment by noyg** [comment]
one more question: how should I go about requiring the latest version with `grant-express`?

**Comment by simov** [comment]
Take a look at the [Alternative Require](https://github.com/simov/grant#alternative-require) section in the documentation.

```js
var Grant = require('grant').express()
```

**Comment by simov** [comment]
:wave: version 3.5.4 is published on NPM :tada:
