### ISSUE TITLE
CORS issue with Facebook/Twitter in Backbone request

### ISSUE THREAD

**Issue by jgauna** [simov/grant#43]
Hello. I configured grant on my hapijs server and it's working great but when I try to make a request to ```myappp:9000/connect/facebook``` (as well with twitter endpoint) using a Backbone model i'm getting a **CORS error** message and model's promise is failing. I've enabled CORS on my hapijs server and I'm pretty sure this is not an issue with grant but maybe you could help me to solve it without change everything on my backend. I've running my frontend in ```myapp.com:3000``` and my backend in ```myapp.com:9000``` and basically what I need is to perform a request from my Backbone frontend and get a redirection to facebook/twitter login screen, after the user log in, the model should be filled with the information i'm returning from my custom endpoint (which is the one that connects to facebook/twitter). Thanks a lot !

**Comment by simov** [comment]
You can't use AJAX request for that. You have to redirect the user instead:

```js
window.location = '/connect/facebook`
```

So it's not what you would expect from a single page app, but the `authorization_code` OAuth2 flow and the similar OAuth1 one, that Grant is concerned with, requires redirecting to a third party server.

**Comment by jgauna** [comment]
Thanks! It works. The final question is, does Grant support sending ```appsecret_proof``` for Facebook security?

**Comment by simov** [comment]
The `appsecret_proof` parameter seems to be used for securing all requests after the initial user login. Check out [here](https://developers.facebook.com/docs/graph-api/securing-requests#generate-proof), the access token and the app secret are used to generate the app secret proof.

**Comment by jgauna** [comment]
yeah but when Grant generates the request it seems not to be sending this ```appsecret_proof=<generated-in-the-server>'```. If i'm missing something I apologize

**Comment by simov** [comment]
Grant is concerned with providing you with `access_token`. You can't have `appsecret_proof` before having an `access_token`:

```php
# the PHP code from the above link
$appsecret_proof= hash_hmac('sha256', $access_token, $app_secret); 
```

You have to generate the `appsecret_proof` **after** you get the `access_token` using Grant.

**Comment by jgauna** [comment]
oh, got it ! Thanks a lot for helping me. Regards.
