### ISSUE TITLE
Hapi example breaks using ^6.0.0 yar

### ISSUE THREAD

**Issue by gigablox** [simov/grant#44]
Due to breaking changes in the [yar](https://github.com/hapijs/yar) plugin, the Hapi example breaks.

**Comment by simov** [comment]
I see. I'll take a look at it tomorrow.

**Comment by simov** [comment]
Version 3.5.5 with the fix is published on NPM. Let me know if you have any problems.

**Comment by gigablox** [comment]
Thank you for the quick turn around @simov. Works great.
