### ISSUE TITLE
User/password authentication strategy / custom oAuth provider

### ISSUE THREAD

**Issue by dj-hedgehog** [simov/grant#50]
I just started a new webapp-project using the application framework Strapi which offers authentication via grant. I want my own authentication in the webapp but am "forced" to use grant.

Is there an easy way to set up/fake my own oAuth provider, will I need to use middleware like [koa-oauth-server](https://github.com/oauthjs/koa-oauth-server) or is there even a simple user/pw strategy for grant?

**Comment by simov** [comment]
Grant is only concerned with *OAuth1.0* and its *OAuth2* counterpart, the *Authorization Code Grant* flow.

So you are going to need an OAuth server (provider) like *koa-oauth-server*. Then you need to setup a [Custom Provider](https://github.com/simov/grant#custom-providers) in Grant pointing to your own application server.

**Comment by dj-hedgehog** [comment]
Ok, thanks for explaining the scope of this project.

**Comment by simov** [comment]
I'm looking at the [Strapi docs](http://strapi.io/documentation/users) right now. It seems that they support what you want. Grant is used only when you login your user using their social network accounts. See the [Local Registration](http://strapi.io/documentation/users#local-registration), it does not use OAuth.
