### ISSUE TITLE
Problem when using multiple scopes in facebook

### ISSUE THREAD

**Issue by Pitchlab** [simov/grant#53]
Hi, 

I am using grant express and trying to make the facebook example work. The twitter and e.g. moves examples work fine. With facebook there is a problem though. After testing it occurs only when there are multiple scopes defined in the config.

```
{
  "server": {
    "protocol": "http",
    "host": "localhost:3000"
  },
  "facebook": {
    "key": "(key)",
    "secret": "(secret)",
    "callback": "/handle_facebook_callback",
    "scope": [
      "public_profile",      
      "user_groups",
      "user_likes"
    ]
  }
}

```
When running, facebook fails to properly redirect back and the query string in the debug shows the scope parameters as url encoded comma separated list: 

`...&scope=public_profile%2Cuser_groups%2Cuser_likes
`

With a facebook error message. "Sorry, something went wrong."

When I replace (manually) in the query string with 

`...&scope=public_profile&scope=user_groups&scope=user_likes
`

it works fine. Regular commas also don't work manually in the querystring.

What am I doing wrong? I am inclined to think I am missing something totally obvious...

Thanks!

**Comment by simov** [comment]
Seems to be working [here](https://grant-oauth.herokuapp.com). What exactly is the error message returned from Facebook?

**Comment by Pitchlab** [comment]
Hi

The site you gave gives me the same error, so I tried a different browser
for good measure. Safari does work. (My) latest version chrome doesn't
(Mac, Yosemite) Weird.

Update: turning off all extensions made it work on chrome as well. Must be
some interference there. As I suspected, something stupid from my side...
Thanks for looking into this.

......................................................................................................
......................................................................................................
*Erik van der Pluijm / *Creative Director & Founder / Thirty X
<http://www.thirty-x.com>
....................................................................
..................................
......................................................................................................


Check out our new book: Design A Better Business! <http://bit.ly/MaDBP>
....................................................................
..................................
......................................................................................................
Prinsengracht 326 ST  /  1016HX Amsterdam  /  NL  /  +31 6 1250 4841 /
Facebook <https://www.facebook.com/ThirtyX>  /  Twitter
<https://twitter.com/erikvdpluijm> /  Instagram
<http://instagram.com/ubilaz>
....................................................................
..................................
......................................................................................................

**Comment by simov** [comment]
No problem.
