### ISSUE TITLE
grant-express app.use(session({secret:'grant'})) question

### ISSUE THREAD

**Issue by LinkTree3** [simov/grant#54]
Hi, this is not really an issue just a question I couldn't find answer to anywhere.
What is the secret: 'grant' part stands for? I see it in different forms everywhere like secret: 'very secret'
am I supposed to replace 'grant'/'very secret' with a different value? what is it used for in the session function?

Thank you very much!

**Comment by simov** [comment]
You should definitely change that value. From the [express-session](https://github.com/expressjs/session#secret) docs:

> This is the secret used to sign the session ID cookie. This can be either a string for a single secret, or an array of multiple secrets. If an array of secrets is provided, only the first element will be used to sign the session ID cookie, while all the elements will be considered when verifying the signature in requests.

**Comment by LinkTree3** [comment]
Thank you for the quick response! :+1:
