### ISSUE TITLE
Change provider config dynamically within the backend

### ISSUE THREAD

**Issue by arjanfrans** [simov/grant#57]
From what I understand, is that you can override provider configuration by posting a form to an override route. 

I need to override the provider config, but this is not controlled from a form. I have a database that contains keys and secrets. I want to override provider configurations within my backend application, by doing a query to my database to get the `key` and `secret` from a provider.

I achieved this by putting in a callback that is called when a connect is done (not a very elegant solution though):
https://gist.github.com/arjanfrans/71c180e7b3274545e2a500b2f8db2233#file-express-js-L10
https://gist.github.com/arjanfrans/71c180e7b3274545e2a500b2f8db2233#file-express-js-L71

Inside this callback I do my database query and then override the config with my `key` and `secret` added.

I basically need the dynamic override ride, without the form part. Is what I am trying to achieve possible with the current version of Grant?

**Comment by simov** [comment]
The easiest way would be this:
```js
// third party module
var qs = require('qs')
// your Express route
app.get('/connect_facebook', (req, res) => {
  // get key and secret from the database and then
  res.redirect('/connect/facebook?' + qs.stringify({key: '...', secret: '...', ...}))
})
```

**Comment by arjanfrans** [comment]
Does this mean that the route can not be the same? I'd like to keep my own route as `/connect/:provider`.

**Comment by simov** [comment]
`/connect/:provider` is reserved route for Grant. You have to use something else for your stuff.

Alternatively you can use the [path prefix](https://github.com/simov/grant#path-prefix) option to achieve what you want:

```js
app.use('/grant', grant)
app.get('/connect/facebook', (req, res) => {
  // get key and secret from the database and then
  res.redirect('/grant/connect/facebook?' + qs.stringify({key: '...', secret: '...', ...}))
})
```

**Comment by arjanfrans** [comment]
Alright, thanks!
