### ISSUE TITLE
Use jwt instead of cookie?

### ISSUE THREAD

**Issue by isaiahgrey93** [simov/grant#58]
I would like to use response data from each provider to create a json web token instead of the generated cookie.

How might I be able to do this using grant?

**Comment by simov** [comment]
Grant uses cookies and session to persist state between the OAuth steps (redirects). After the OAuth flow is complete you can generate the jwt token inside your callback route and then you can remove the flow data from the session.

Let me know if that makes sense.

**Comment by simov** [comment]
@isaiahgrey93 you may find this [example](https://github.com/simov/grant/tree/master/examples/jwt) interesting.
