### ISSUE TITLE
Supply additional headers with request

### ISSUE THREAD

**Issue by robinvdvleuten** [simov/grant#67]
Hi there,

First, big props for this lib! Very easy to setup 👍  I am trying to setup a connection with the discogs oauth api, but they require to send an additional user-agent header. How can I configure this in the grant lib? Here's my setup:

```js
var express = require('express')
var logger = require('morgan')
var session = require('express-session')
var Grant = require('grant-express')

var grant = new Grant({
  'server': {
    protocol: 'http',
    transport: 'session',
    state: true,
  },
  'discogs': {
    key: process.env.DISCOGS_CONSUMER_KEY,
    secret: process.env.DISCOGS_CONSUMER_KEY,
    callback: '/handle_discogs_callback',
  },
})

var app = express()
app.use(logger('dev'))
app.use(session({ name: 'grant', secret: 'very secret', saveUninitialized: false, resave: false }))
app.use(grant)

app.get('/handle_discogs_callback', (req, res) => {
  res.end(JSON.stringify(req.query))
});

app.listen(4000, () => {
  console.log('Express server listening on port ' + 4000)
});
```

**Comment by simov** [comment]
I see, they probably changed how their OAuth flow behaves. I'm going to add this header and a test for it.

Intentionally there is no way to add custom headers, because I want everything non OAuth compliant documented in my code, like this one. Of course this approach can break my code but I prefer it that way. I'll publish the patch later today.

Thanks for the feedback!

**Comment by robinvdvleuten** [comment]
@simov thank for the quick response! I'll wait for the patch then 😌

**Comment by simov** [comment]
Version 3.6.5 is published with the fix. 

Currently the user-agent is non configurable meaning it will always be called `Grant` during the OAuth flow.

:tada:

**Comment by robinvdvleuten** [comment]
@simov thanks! it works as expected 👌
