### ISSUE TITLE
Does not work with hapi-auth-jwt2

### ISSUE THREAD

**Issue by TBoonX** [simov/grant#68]
If I add to my working code the npm module hapi-auth-jwt2, then all calls to /connect/provider returns 401.
How I added it:
as plugin in hapi _require('hapi-auth-jwt2')_
with a configuration 
```
    server.auth.strategy('jwt', 'jwt', {
      key: config.JWT.SERIAL,
      validateFunc: jwt.validate,
      verifyOptions: {
        algorithms: [ config.JWT.ALGORITHM ],
        ignoreExpiration: true
      },
      headerKey: config.JWT.HEADER
    });

    server.auth.default('jwt');
```
Then the routes for grant have the configuration for disable jwt:
```
    config: {
      auth: false
    }
```

It returns the body
`{"statusCode":401,"error":"Unauthorized","message":"Missing authentication"}`
and the headers
```
HTTP/1.1 401 Unauthorized
WWW-Authenticate: Token
content-type: application/json; charset=utf-8
cache-control: no-cache
vary: accept-encoding
content-encoding: gzip
Date: Wed, 26 Oct 2016 08:30:58 GMT
Connection: keep-alive
Transfer-Encoding: chunked
```

Do you have an idea why this is happening and could it be resolved by me or you?

**Comment by simov** [comment]
How do you pass the `config: {auth: false}` to the Grant routes? I don't think that's currently possible.

**Comment by TBoonX** [comment]
```
server.route({
    method: 'GET',
    path: '/handle_github_callback',
    handler: function(req, res) {
      //Continue with the token
      //Remark: third parameter have to be the name of the provider as listet for purest
      handlers.handleOAuth2Token(req, res, 'github');
    },
    config: {
      auth: false
    }
  });
```
this disables hapi-auth-jwt2 for the route.

**Comment by simov** [comment]
This options should be added to the Grant's internal `/connect` routes but that's currently not possible.

I don't see an option to filter out those routes in `hapi-auth-jwt2` either, so I'm thinking about implementing a `config` object support for Grant.

**Comment by TBoonX** [comment]
You are right!
I solved it for me with removing `server.auth.default('jwt');` in my server.js and enabling jwt just for routes which needs it.
For me it is resolved but perhaps your proposal should be considered in the future.
Thanks

**Comment by Rub21** [comment]
hey @TBoonX , 

>  enabling jwt just for routes which needs it.

how did you enable for specific routes?

**Comment by TBoonX** [comment]
@Rub21 
In your routes:
```
server.route({
        ..
        config: {
            ...
            auth: 'jwt'
        }
    });
```
in your server: (something like that)
```
server.auth.strategy('jwt', 'jwt', {
            key: SERIAL,
            validateFunc: validate,
            verifyOptions: {
                algorithms: [ALGORITHM],
                ignoreExpiration: true
            },
            headerKey: HEADER
        });
```
