### ISSUE TITLE
Using Grant without sessions

### ISSUE THREAD

**Issue by Bramzor** [simov/grant#69]
For our APP, we arent using any Sessions but instead, using JWT tokens. Is there a way to use Grant without having to use sessions?

**Comment by simov** [comment]
Hi @Bramzor can you read through this thread https://github.com/simov/grant/issues/59

**Comment by Bramzor** [comment]
Hi @simov, thanks for showing me that thread. Is exactly what I'm facing. So the only solution is including sessions (which I just got rid off thanks the JWT tokens). Checked https://github.com/simov/grant/blob/master/examples/jwt/app.js and it might be a solution to create an empty session handler (which does nothing) just to pass the variables.

**Comment by simov** [comment]
Yes the session in Grant is used only as a temporary state. It's not being used for anything else and you can delete it after the OAuth flow is complete.

Can you open up another issue for your other question in the Purest issue tracker?
