### ISSUE TITLE
Koa2 implementation question

### ISSUE THREAD

**Issue by sleewoo** [simov/grant#70]
Any thoughts on how to handle Koa consumer after Koa2 released?

Chrome 55 released today and there is progress on a Node7 release that will ship with V8 5.5.
Node may land with official async/await support in less than a month.
Same for Koa2.

Would you ship a Koa2 version or replace existing one?
Thanks.

**Comment by simov** [comment]
Last time I checked Grant was working fine with Koa2. Check out my comment [here](https://github.com/simov/grant/pull/62#issuecomment-243443866).

I know that support for generators will be dropped in Koa3 so I think that would be a breaking change here as well. Using async/await functions for your Koa routes shouldn't be a problem, it's just that Grant is going to use a generator function for its routes.

I'm usually fairly quick to respond and apply a patch if needed so you just have to let me know if something isn't working.

**Comment by sleewoo** [comment]
mm, sorry, i'm not aware of any Koa3, did i miss something?

AFAIK, current version is v1 and it uses generators.
Next version is v2 and will be released (pretty soon) when Node will natively support async/await.
v2 does not allow generators middleware, everything should be async/await.

So when v2 released, will you support both versions or would async/await version replace generators one?

Thanks.

**Comment by simov** [comment]
Check out this [section](https://github.com/koajs/koa/tree/v2.x#old-signature-middleware-v1x---deprecated):

> Old signature middleware (v1.x) support will be removed in v3

> Koa v2.x will try to convert legacy signature, generator middleware on app.use, using koa-convert. It is however recommended that you choose to migrate all v1.x middleware as soon as possible.

From my prevous [comment](https://github.com/simov/grant/pull/62#issuecomment-243443866):

> https://github.com/simov/grant/commit/7a7e10c2f4f14d77bed356c606165330d020ee63 works for both Koa1.x and Koa2.x. For Koa2.x you have to update the koa-mount module to v2.x as well.

Again:

Grant currently works with both Koa1 and Koa2, however it won't work with Koa3 out of the box.

Let me know if something isn't working for you with Koa2.

**Comment by sleewoo** [comment]
thanks for patience :)
will give it another try and reply with results

**Comment by sleewoo** [comment]
works perfect!
was cooking it wrong.
thank you.

**Comment by simov** [comment]
No problem, thanks for the feedback!
