### ISSUE TITLE
Generate a JWT and Send to Client

### ISSUE THREAD

**Issue by kevincollins7** [simov/grant#72]
Hello,

This is not an issue with Grant but maybe you guys could help me out. I've got Grant working on my API running on http://localhost:3000 and I've got an Angular2 app running on http://localhost:4200.

If I setup my Angular2 app login screen with a Google Auth button that redirects the user window to http://localhost:3000/connect/google (window.location.href='http://localhost:3000/connect/google") I get the Google login page - Great! 

This is where I get lost though. I'd like to have my API take the Google access_token, call the Google People API to get the profile, verify that user email against my own set of users, if the user exists then generate a jsonwebtoken and send that back to the Angular2 app. If I set the callback to call my API though (ex. http://localhost:3000/handle_google_callback) then the JSON Web Token I generate is not available to my front end.

Ways I see to accomplish this are to set the callback to something like 'http://localhost:4200/auth' and have the Angular2 app take the access_token and send it back to my API for further processing. Or by any chance are you familiar with a better way?

**Comment by simov** [comment]
Hi @kevincollins7,

Take a look at the [JWT example](https://github.com/simov/grant/tree/master/examples/jwt).

You only have to add that additional step to verify the user's email against your database. In the end this examples returns a JSON response to the `/handle_facebook_callback` route. There you should have some browser side logic to redirect the user to where it was in your app before clicking on the login button.

**Comment by kevincollins7** [comment]
Thanks @simov 

So confirming the user exists and creating the jwt is the easy part. Got that working. I guess my question is - does it makes sense for me to have the callback actually set to the frontend and not the API. I've got something working right now where in my API on :3000 I have the callback set to the frontend on :4200/auth. That /auth route actually takes the access_token from the GET request and makes a new call to my API to generate a JWT.

Does that make sense? This is my first shot at implementing an OAuth solution so I'm just trying to be sure I'm being secure here.

**Comment by simov** [comment]
Grant internally is redirecting you to whatever `callback` URL you specify. It doesn't matter where it is as long as it is reachable. In the end you have to _response_ back to the user.

I'm not sure I understand your scenario exactly.

**Comment by kevincollins7** [comment]
No worries @simov I don't want to have you stuck with an open issue when really nothing is broken with Grant. I have a working solution using Grant now and I'm going to run it by some of my teammates so you can close this issue. If you'd like to connect outside of this ticket I could demo my scenario and current solution for you. Just let me know!

**Comment by simov** [comment]
I'm glad it worked out for you. You can explain what you did here if you want. It might be useful to someone else.

**Comment by kevincollins7** [comment]
Definitely! Here is my scenario. We are building a web application using Angular2 and an API using Koa2.

Running locally:
http://localhost:3000 is the API
http://localhost:4200 is the Angular2 application

Grant is installed and running on the API. 

On the Angular2 app I built a login form (http://localhost:4200/login) with a button that directs the browser to: http://localhost:3000/connect/google

So here the user logs in to Google and then the callback is executed.

The callback for Grant on the API is set to http://localhost:4200/auth

The /auth route in the Angular2 app takes the access_token in the URI from the callback and then makes a call to: http://localhost:3000/google

The /google API endpoint does most of the work:
- Calls the Google People API to get the user email address
- Looks up the user Google email address in our data to see if there is a match
- If there is a match, create a jwt and send in the response

At this point the /auth route in the Angular2 app takes the response from that API call, stores the jwt in Local Storage and redirects the browser to the default page of the application.

I still have quite a bit of work to do but this is a very high level overview. I just wanted to make sure this solution wasn't crazy. Open to any feedback.

Thanks!

**Comment by simov** [comment]
Sounds reasonable. 

Your JWT [should expire](https://github.com/simov/grant/blob/master/examples/jwt/jwt.js#L23) at some point (1 year is too long). How are you going to refresh it?

Here is one interesting [thread](http://stackoverflow.com/questions/26739167/jwt-json-web-token-automatic-prolongation-of-expiration) about it.

**Comment by kevincollins7** [comment]
Yep definitely that's actually the next thing I've got to work on so thanks for the links! Something like staying valid for X days then requiring a refresh will be the goal. There is also this library:

https://github.com/auth0/angular2-jwt

Which l've only just started glancing at.

Thanks for taking the time to read my process!

**Comment by simov** [comment]
:+1:
