### ISSUE TITLE
Copy.com is discontinued

### ISSUE THREAD

**Issue by franz-josef-kaiser** [simov/grant#73]
I just saw that [copy.com](https://copy.com/) has ended its live and so has their OAuth endpoint and developer documentation. They [can safely be removed](https://github.com/simov/grant/blob/057e9224308191b91c9e4b6fdf5896284c85d355/README.md#150-supported-providers--oauth-playground) from the `README`.

**Comment by simov** [comment]
That's a good idea, I think there are a few others discontinued from that list, but it'll be too much work to find them all.

**Comment by simov** [comment]
I also removed `beatsmusic` https://github.com/simov/grant/commit/37fd75e05efd80570bda917834f600a877cc0b35 because they were acquired by Apple.
