### ISSUE TITLE
How does this project compare to Passport?

### ISSUE THREAD

**Issue by corysimmons** [simov/grant#77]
Just curious. Didn't see a Gitter or anything.

**Comment by simov** [comment]
Grant is only concerned with [OAuth 1.0](http://oauthbible.com/#oauth-10a-three-legged) and [OAuth 2.0 authorization code](http://oauthbible.com/#oauth-2-three-legged) flows.

As to what Passport offers you'll have to ask in their issue tracker.

**Comment by corysimmons** [comment]
It seems like the same thing except Passport offers email auth as well as OAuth providers.
The huge difference being Grant looks much simpler/cleaner.

Any plans on adding email auth?

**Comment by simov** [comment]
Nope, that's the scope of this project.

Grant is only a middleware, like any other, regarding OAuth, meaning that you can add another middleware for email auth to your app.

**Comment by corysimmons** [comment]
Fair enough.
