### ISSUE TITLE
New koa consumer module fail to load

### ISSUE THREAD

**Issue by slaskis** [simov/grant#8]
I think you're doing the right thing to split the consumers out of the main module but because I don't have express in my app it fails to load express when I require `grant-koa` because all consumers are required in `index.js`.

Perhaps they should be split into separate repositories with separate tests, so they're tested more like they will be used instead?

**Comment by simov** [comment]
You are correct I left the `express` require for backward compatibility with version 1.x I'll remove it.

**Comment by simov** [comment]
@slaskis version 3.0.2 was just released https://www.npmjs.com/package/grant

Thanks for reporting this bug!

As for why I'm keeping the code in one place read this comment https://github.com/simov/grant/issues/7#issuecomment-80721036

**Comment by slaskis** [comment]
That was quick, thanks!
