### ISSUE TITLE
[SUGGESTION]: Add google OATH api to examples.

### ISSUE THREAD

**Issue by wotsyula** [simov/grant#81]
The examples directory only contain examples for Facebook and Twitter OAUTH. Had to spend over an 2 hours looking at code and debugging to get google to work. An example of getting user profile with google api (and purest) would be great. If not for me then at least for the next guy.

**Comment by simov** [comment]
Hi, @wotsyula, thanks for your suggestion and for keeping it cool after spending 2 hours of your time trying to get it working. I understand your frustration.

I try to keep the documentation and the examples as concise as possible. Facebook and Twitter are picked only for the sole purpose of demonstrating the configuration for OAuth2 and OAuth1 respectively. I could've picked any other two, and besides that more than 170 other OAuth providers are not present in the examples folder.

I published an [article](https://scotch.io/tutorials/implement-oauth-into-your-express-koa-or-hapi-applications-using-grant) back then about Grant, probably a link to it somewhere in the Readme could be helpful?
