### ISSUE TITLE
setting the scope_delimiter value does not get passed as actual delimiter

### ISSUE THREAD

**Issue by nigeltiany** [simov/grant#84]
When the scope_delimiter is set as e.g ```"+"```, the delimiter is used as ```%2B``` in the request.

**Comment by simov** [comment]
Yes, all delimiters: `,`, ` ` (empty space) and `+` are being escaped:

```bash
> encodeURI(',. .+')
',.%20.+'
> encodeURIComponent(',. .+')
'%2C.%20.%2B'
> querystring.stringify({a: ',. .+'})
'a=%2C.%20.%2B'
> qs.stringify({a: ',. .+'})
'a=%2C.%20.%2B'
```

From the above example only the [encodeURI](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI) function does not encode the _unreserved_ URI characters. [encodeURIComponent](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) on the other hand, the built-in [querystring](https://nodejs.org/dist/latest-v8.x/docs/api/querystring.html) module, and the [qs](https://www.npmjs.com/package/qs) module that Grant uses internally, all encode the _unreserved_ URI characters. [qs](https://www.npmjs.com/package/qs) additionally encodes `[!'()*]` by default also known as RFC3986.

---

Currently only [Unsplash](https://unsplash.com) uses `+` as scope delimiter and [does not expect](https://unsplash.com/documentation#user-authentication) it to be encoded. Considering that this is a deviation from the standard, an explicit code is set:

https://github.com/simov/grant/blob/39b61bb51cb1212d37e6fd5f859587a1dc7cdb57/lib/flow/oauth2.js#L36-L41

and a corresponding test:

https://github.com/simov/grant/blob/39b61bb51cb1212d37e6fd5f859587a1dc7cdb57/test/flow/oauth2.js#L232-L239

---

@nigeltiany let me know what do you think.
