### ISSUE TITLE
Hapi v17 support

### ISSUE THREAD

**Issue by illarionvk** [simov/grant#87]
Thank you for creating the library; I enjoy using it with Hapi to authenticate my apps in Shopify stores.

[Hapi v17](https://github.com/hapijs/hapi/issues/3658) has introduced a lot of breaking changes and I can't make Grant Hapi plugin work with the new version.

Are you considering upgrading your Hapi plugin to support Hapi v17 in the near future?

**Comment by simov** [comment]
Yes, it will most likely require a separate [consumer](https://github.com/simov/grant/tree/master/lib/consumer) similarly to `koa2`. I can't give you exact timeframe, but it's definitely on my radar. I'll let you know once I have something ready.

**Comment by simov** [comment]
@illarionvk Hapi v17 support landed in v4.1.0 :rocket: :sparkles: 

Check out the [changelog](https://github.com/simov/grant/blob/master/CHANGELOG.md#v400-20180314) for any potential breaking changes in v4.x

Let me know if you have any issues with it.

**Comment by illarionvk** [comment]
The new Hapi v17 consumer works well for me so far. Thank you!
