### ISSUE TITLE
Cannot find module 'request-logs'

### ISSUE THREAD

**Issue by ifedapoolarewaju** [simov/grant#88]
after updating to the latest version of `grant.js` on [uppy-server](https://github.com/transloadit/uppy-server), I am getting the following error.

<img width="966" alt="screen shot 2018-03-15 at 12 07 49 am" src="https://user-images.githubusercontent.com/8383781/37435994-18a6b64c-27e6-11e8-8eb5-d78778ee9ff1.png">

is this expected? Should `request-logs` be installed as a dependency?

**Comment by simov** [comment]
Do you have any environment variables set? This dependency should be needed only when the `DEBUG` environment variable is set. I should probably remove it anyway as it can cause issues.

**Comment by ifedapoolarewaju** [comment]
I am setting `export DEBUG="to some value"`, but I think this implicit behaviour might be undesirable since the env variable set might be unrelated with the library.  Especially since `request-logs` is set as a devDependency.

**Comment by simov** [comment]
Yep, I'll change that, I'll let you know once it's ready.

**Comment by simov** [comment]
@ifedapoolarewaju I've published `v4.0.1` you should be able to remove the `request-logs` dependency now.

Thanks for the feedback :+1: 

Let me know if you find anything else!
