### ISSUE TITLE
Design pattern for multiple, independents scopes for the same provider

### ISSUE THREAD

**Issue by mechanical-turk** [simov/grant#90]
Hi,

We are having a hard time figuring out how to tackle the following issue:

Let's say we want two separate OAUTH integrations for Google Calendar and Google Contacts. Since we want these to be processed differently, we'd like to assign different callbacks for them. However, because they belong to the same provider, we can only list one callback under `google` when we are initializing the grant object for the middleware.

Is there a pattern in grant that would let us create 2 different callbacks for two scopes of the same provider?

Thanks.

**Comment by simov** [comment]
Hi,

These are called [Static Overrides](https://github.com/simov/grant#static-overrides) ([example](https://github.com/simov/grant/blob/master/examples/static-override/config.json)).

You can override any option. Also you can have as many callbacks as you want:

```js
{
  "server": {
    "protocol": "https",
    "host": "website.com",
    "transport": "session",
    "state": true
  },
  "google": {
    "key": "[APP_ID]",
    "secret": "[APP_SECRET]",
    "calendar": {
      "scope": [
        "..."
      ],
      "callback": "/calendar_callback"
    },
    "contacts": {
      "scope": [
        "..."
      ],
      "callback": "/contacts_callback"
    }
  }
}
```

Then you have to navigate to:

- /connect/google/calendar
- /connect/google/contacts

And on you server you'll have two separate routes to handle each login respectively:

- /calendar_callback
- /contacts_callback

**Comment by mechanical-turk** [comment]
@simov thank you so much. this was really helpful
