### ISSUE TITLE
Port is hard coded in express-4 example

### ISSUE THREAD

**Issue by melvincarvalho** [simov/grant#97]
Port is hard coded to 3000 in 

https://github.com/simov/grant/blob/master/examples/express-4/app.js

Would it be better to change the magic number into a variable or pull it in from the config?

**Comment by simov** [comment]
Well that's just an example and I try to keep it short and straightforward. You most probably won't hardcode it in a production app. All examples follow the same pattern and the port is hardcoded in all of them.
