### ISSUE TITLE
Supporting user profile gathering out of the box?

### ISSUE THREAD

**Issue by jgomer2001** [simov/grant#99]
This is maybe not in the scope of grant, but it would be nice to have means to easily obtain user profile data. 

As the example shows https://github.com/simov/grant/blob/master/examples/user-profile/app.js, you have to have prior knowledge of the endpoints needed to get user data for every supported provider. 

To build a system that relies on external providers for authentication, you have to go through docs, do some coding and then testing. I think built-in support of it would make grant be more outstanding, even beating passport.js...

**Comment by simov** [comment]
I agree. I was thinking about compiling a list of all user endpoints. In fact I had something similar in one of my other modules [here](https://github.com/simov/purest/blob/2.x/test/request/get.js), and the actual URLs are [here](https://github.com/simov/purest/blob/2.x/config/providers.json). 

So it's doable, it can be implemented either as additional option in grant or a separate middleware, that when enabled makes that additional request for you. Of course the implementation won't try to parse the result in any way, it will dump the JSON response of the user endpoint as it is.

**Comment by jgomer2001** [comment]
Would be great!

**Comment by simov** [comment]
Check out [grant-profile](https://github.com/simov/grant-profile) about the ongoing progress on this issue. Additional background information can be found in this PR https://github.com/simov/grant/pull/113

**Comment by simov** [comment]
`grant-profile` was embedded into Grant v5.1.0 and it have to be enabled as a [response option](https://github.com/simov/grant#profile) /cc @daffl
